### ISSUE TITLE
Request New Feature For Pactus GUI

### ISSUE THREAD

**Issue by aboka2k** [pactus-project/pactus#1080]
I would like to request the following enhancement for the Pactus GUI. Given that Pactus is committed to being a decentralized, user-friendly, and fair platform, it's important that the interface reflects these values.

All these suggestions are aimed at enhancing user-friendliness and streamlining the interface.

1) Combine both Validator/Reward pair on the same row

2) Add address management feature: Automatically mark Validators that have unbonded. Include the option to hide/unhide them.

3) When adding a new address, it will creates both the Validator and its corresponding Reward as a pair simultaneously.

Thank you,

**Comment by b00f** [comment]
@aboka2k Let's move this issue to the new repository for the GUI here: https://github.com/pactus-project/pactus-gui

**Comment by Ja7ad** [comment]
@aboka2k Features request moved to this issue for implementation:

https://github.com/pactus-project/pactus/issues/1555
