### ISSUE TITLE
fix: grpc wallet creation when password is provided to daemon

### ISSUE THREAD

**Issue by ChandlerFerry** [pactus-project/pactus#1155]
### How To Reproduce

1. daemon -p=`<PASSWORD>`
2. GRPC call Create Wallet
3. INVALID PASSWORD
> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.

### What Happened

https://github.com/pactus-project/pactus/blob/main/www/grpc/wallet.go#L69 explodes because "" != `<PASSWORD>` hence password is invalid

### Expected Behavior

Create the wallet

### Environment

- **Operation System:**
- **Pactus Version:**1.10? beta
- **Go Version:**

**Comment by b00f** [comment]
@ChandlerFerry 

Thanks for reporting this issue, and we are so sorry about the bad experience you had. We didn't test this API properly, and it is really our fault.
Just to inform you, we are currently working on implementing a "wallet-service" that manages wallets internally. This is why we haven't yet had the chance to carefully review the details of the wallet APIs.
