### ISSUE TITLE
Wallet Service Requirements

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1209]
The wallet service is a service that starts by running the node and closes when the node shuts down. 
It has its own context and is responsible for creating new wallets, loading/unloading wallets, and locking/unlocking wallets. 
The best place for wallet service is under the `wallet` package.

The list of wallets can be obtained either from the list of files inside the wallet folder or from a `settings.json` file. 
The first approach is simple; for the second approach, we need to handle it globally, as we may need to store more information in the future.

The wallet service should securely hold wallet passwords in memory and destroy them on lock timeout. 
Please check Bitcoin as an example of how they store wallet passwords in memory and safely zero them out. We can use [https://github.com/awnumar/memguard](https://github.com/awnumar/memguard/blob/master/examples/stdin/stdin.go) package as well.

The APIs should be compatible as much as possible with Bitcoin APIs, since many developers are familiar with these APIs: https://developer.bitcoin.org/reference/rpc/#wallet-rpcs

**Comment by b00f** [comment]
Once the Wallet service gets ready we can implement [Wallet APIs](#1210)

**Comment by Ja7ad** [comment]
@b00f Done?

**Comment by b00f** [comment]
It's done. Thanks @Ja7ad  and @ambersun1234
