### ISSUE TITLE
Wallet Service APIs

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1210]
Here is the list of APIs that wallet service should provide

- [x] Create Wallet  - Create a wallet and return the mnemonic
- [x]  Restore Wallet - Recover wallet by given mnemonic
- [x]  Load Wallet - Load wallet by name
- [x]  Unload Wallet - Unload wallet by name
- [x]  Get New Address - Get new address based on the given address type
- [x]  Get Total Balance - Get the total balance of the wallet
- [ ]  Get Total Stake - Get the total stake of the wallet
- [ ] Get Address Info - Get the address info for the given address
- [ ] Set Label - Set label for the given address
- [ ] Get Wallet Info - Return the information about wallet
- [ ] List Wallets - Return the list of wallets inside wallet directory
- [ ] List Address - Return the list of addresses in wallet, it accepts Purpose as argument

**Comment by Ja7ad** [comment]
@b00f This PR https://github.com/pactus-project/pactus/pull/1241 make complete this issue?

**Comment by ambersun1234** [comment]
@Ja7ad There're some APIs still work in progress

**Comment by Ja7ad** [comment]
> @Ja7ad There're some APIs still work in progress

Before implementation please review [pip-23](https://pips.pactus.org/PIPs/pip-23) for implementation.
