### ISSUE TITLE
Invalid mnenomic error while recovering testnet wallet

### ISSUE THREAD

**Issue by Fabryprog** [pactus-project/pactus#1254]
## Description

To restart my testnet validator, I tried to recovery my wallet but I had an **Invalid mnenomic** error

### How To Reproduce

Using an empty data folder, I launched the command

pactus-daemon init --testnet --restore seeds_word_1 seeds_word_2 etc

### What Happened

The ouput show only an **Invalid mnenomic error**

### Expected Behavior

My wallet was restore

### Extra

No extra

### Environment

- Linux (Docker)
- Latest (1.1.3)

**Comment by kehiy** [comment]
Hi, please provide seeds like this:

`pactus-daemon init --testnet --restore="seeds_word_1 seeds_word_2 etc"`

Also, that's better to use wallet binary instead of running a node!

For wallet you can use recover command. And then use menomic as input.

**Comment by Fabryprog** [comment]
Good!

I found the documentation section here: https://pactus.org/user-guides/pactus-daemon/

So, It is ok! Closing this issue :-)
