### ISSUE TITLE
Adding connection stats to HTTP module

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1275]
In PR #1273, we have added connection stats to the gRPC node-info API. This will be especially helpful for debugging and monitoring the node to include this information in the HTTP module at [NodeHandler](https://github.com/pactus-project/pactus/blob/34f0b99d877eb0c31c10e220deb3d7d947a441bd/www/http/network.go#L90).

Please remove "Addrs," which is duplicated with "LocalAddr," in the same PR.

**Comment by ambersun1234** [comment]
Also need to rename `addrs` field name to `local_addr` in `network.proto`
