### ISSUE TITLE
Panic when get total account balance

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1322]
## Description

When get total balance panic happen on nil conn.

### What Happened

![image](https://github.com/pactus-project/pactus/assets/56496801/e4ba7889-603c-4dc7-9d5a-91c20d0f0cb1)

**Comment by b00f** [comment]
## How to Reproduce:

1. Build the latest code and run the Pactus blockchain locally. Localnet works as well. Read more [here](https://github.com/pactus-project/pactus/blob/main/docs/install.md).
2. In a separate terminal, run the following commands:
    ```
    ./build/pactus-shell wallet load-wallet --wallet-name "default_wallet"
    ./build/pactus-shell wallet get-total-balance --wallet-name "default_wallet"
    ```
3. The Pactus node crashes.

## How to Fix

1. First, ensure the node does not crash on gRPC API failure. Try to catch the panic and log it.
2. Secondly, fix the above crash.

**Comment by b00f** [comment]
@akbariandev any progress on this issue?
