### ISSUE TITLE
Improve Node Startup by Optimizing Availability Score Calculation

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1337]
## Description:

When the node starts, it calculates availability scores by scanning the last 60,000 blocks and loading their certificates. This process is time-consuming as it involves loading the entire block data. 

### Proposed Solution:

Optimize the process by loading only the certificates without loading the entire block data. This should significantly speed up the calculation of availability scores.

### Steps to Reproduce:
1. Start the node.
2. Observe the time taken to scan and load the last 60,000 blocks for availability score calculation.

**Comment by Ja7ad** [comment]
> ## Description:
> When the node starts, it calculates availability scores by scanning the last 6000 blocks and loading their certificates. This process is time-consuming as it involves loading the entire block data.
> 
> ### Proposed Solution:
> Optimize the process by loading only the certificates without loading the entire block data. This should significantly speed up the calculation of availability scores.
> 
> ### Steps to Reproduce:
> 1. Start the node.
> 2. Observe the time taken to scan and load the last 6000 blocks for availability score calculation.

Score Window is 60000:

https://github.com/pactus-project/pactus/blob/3c0cf1d8372b01f2ec7ac3f2a43fae77d2dd34c9/state/state.go#L100
