### ISSUE TITLE
Can't after update 1.2.0

### ISSUE THREAD

**Issue by jackieluong135** [pactus-project/pactus#1359]
![Screenshot 2024-06-21 093218](https://github.com/pactus-project/pactus/assets/105584726/cb7d2a65-f2ab-4da2-aae4-c6cc1a2e2ada)

## Description

>I can't Bond to my validator , after update to version 1.2.0

**Comment by b00f** [comment]
To check the stake, run this command:

```
./pactus-wallet --path /root/node_pactus/pactus-testnet/wallets/default_wallet address all --stake
```
