### ISSUE TITLE
couldn't add to transaction pool

### ISSUE THREAD

**Issue by jackieluong135** [pactus-project/pactus#1374]
## Description

couldn't add to transaction pool.

- **Ubuntu 22.4:**
- **1.2.1-rc1:**
![Screenshot 2024-06-27 083340](https://github.com/pactus-project/pactus/assets/105584726/3f14d0cf-2c95-4282-b64e-bbf97d8a8afa)

**Comment by kehiy** [comment]
@jackieluong135 

There are 2 possibilities:

1. The sender's address is new and not indexed in the network: so you need to send it some PAC first. currently, you can't transfer something that does not exist.
2. Your wallet file does not contain the sender address: run `./pactus-wallet address new` till you reach the sender address.
