### ISSUE TITLE
Inavid credential for gRPC

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1389]
## Description

If user set invalid credential fro gRPC, it won't get any error or even no log is printed.
We need to check the credential before starting the node.

**Comment by Ja7ad** [comment]
> ## Description
> If user set invalid credential fro gRPC, it won't get any error or even no log is printed. We need to check the credential before starting the node.

Where is this issue happen and please more explain about it?

**Comment by b00f** [comment]
In config file, put random string as gRPC basic auth.

**Comment by Ja7ad** [comment]
> In config file, put random string as gRPC basic auth.

Which transport gRPC, gRPC gateway or http?

**Comment by b00f** [comment]
To produce it, open config file and change `basic_auth` to:

```
basic_auth = "abscef"
```

**Comment by Ja7ad** [comment]
> To produce it, open config file and change `basic_auth` to:
> 
> ```
> basic_auth = "abscef"
> ```

This is invalid value and we should prevent on `BasicCheck`
