### ISSUE TITLE
Pruning on New Block 1:1

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1393]
Once a new block is committed, the following operations should be performed:

1. If the node is a Full Node, no action is needed.
2. If the node is a Pruned Node, call the PruneBlock function with the block number equal to LastBlockHeight - RetentionBlocks.

This process ensures that for each new block added, one old block will be removed, keeping the store blocks up to the RetentionBlocks number.

https://pips.pactus.org/PIPs/pip-27#pruning-on-new-block

**Comment by kehiy** [comment]
@b00f @Ja7ad To determine whether a node is a pruned or full node, it's better to pass this information to the store or sync module? Should it be a part of the config?

**Comment by kehiy** [comment]
I think the best way is to pass it to sync and read it from config.

**Comment by b00f** [comment]
@kehiy Based on PIP-27  if the genesis block or block number one exists, it is full node.

![image](https://github.com/pactus-project/pactus/assets/8073510/5de1ec69-d853-4858-92e5-4cf28a117098)

**Comment by kehiy** [comment]
@b00f OK, I'll add it once #1400 got merged.

**Comment by kehiy** [comment]
@b00f @Ja7ad If we check prune mode by checking the genesis block, each node will be pruned if it's a new node.

**Comment by b00f** [comment]
> If we check prune mode by checking the genesis block, each node will be pruned if it's a new node.

Good find, check last certificate exists. If not we are at the genesis state.
