### ISSUE TITLE
Add LastBlockTime to BlockChainInfo API

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1405]
Add new field to [GetBlockchainInfoResponse](https://github.com/pactus-project/pactus/blob/7b6a2dc0e9d9527f8a7a48125b892d8cc4c0354f/www/grpc/proto/blockchain.proto#L161) to report the last block time.

**Comment by ZigBalthazar** [comment]
Hi @b00f 
I am interested to work on this issue

**Comment by Ja7ad** [comment]
> Hi @b00f I am interested to work on this issue

When you complete this task?
