### ISSUE TITLE
Installation returns unexpected error on MacBook

### ISSUE THREAD

**Issue by Mr-HoDL58** [pactus-project/pactus#1436]
## Description

Installation fails on MacOS here is report
[C.txt](https://github.com/user-attachments/files/16378819/C.txt)

### How To Reproduce

Install GUI

### What Happened
Unexpected Error

### Expected Behavior

It to work

### Environment

- MacOS
- 1.3.0

**Comment by b00f** [comment]
Fixed at #1445
