### ISSUE TITLE
Add total Send/Received bundles per type for peers

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1473]
## Describe the problem you'd like to have solved

Currently, we track how many bytes per bundle type have been sent or received from a specific peer. However, knowing the number of bundles as well would be valuable information that we should retain.

### Describe the ideal solution

The ideal solution is to modify the existing code from:

```go
type Peer struct {
...
   ReceivedBytes     map[message.Type]int64
   SentBytes         map[message.Type]int64
}
```

to:

```go
type Peer struct {
...
   ReceivedMetrics   map[message.Type]Metric
   SentMetrics       map[message.Type]Metric
}
```

**Comment by solthereum** [comment]
Hi, @b00f , sorry for leaving comment here without your agreement and respecting the team rule. Because I wanna join your team as full time dev, so I am going to solve issues and challenges as proving of my skill. Could you give me some issue to be solved quickly as test task?
