### ISSUE TITLE
Simplify Transaction APIs by Merging GetRawXTransaction Methods Using oneof in Protocol Buffers

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1480]
### **Describe the problem you'd like to have solved**

The current Transaction APIs have separate RPC methods for retrieving raw details of different types of transactions (e.g., transfer, bond, unbond, withdraw). Each method requires a specific request and returns a response, leading to redundancy in the codebase. The existing structure complicates the API and increases maintenance overhead.

### **Describe the ideal solution**

The ideal solution is to simplify the Transaction APIs by merging all `GetRawXTransaction` methods into a single `GetRawTransaction` method. This unified method would handle different types of transactions using the `oneof` keyword in the Protocol Buffer definition.

The proposed changes are:

**Current API:**
```proto
// GetRawTransferTransaction retrieves raw details of a transfer transaction.
rpc GetRawTransferTransaction(GetRawTransferTransactionRequest)
    returns (GetRawTransactionResponse);

// GetRawBondTransaction retrieves raw details of a bond transaction.
rpc GetRawBondTransaction(GetRawBondTransactionRequest)
    returns (GetRawTransactionResponse);

// GetRawUnbondTransaction retrieves raw details of an unbond transaction.
rpc GetRawUnbondTransaction(GetRawUnbondTransactionRequest)
    returns (GetRawTransactionResponse);

// GetRawWithdrawTransaction retrieves raw details of a withdraw transaction.
rpc GetRawWithdrawTransaction(GetRawWithdrawTransactionRequest)
    returns (GetRawTransactionResponse);
```

**Proposed API:**
```proto
// GetRawTransaction retrieves raw bytes of a transaction.
rpc GetRawTransaction(GetRawTransactionRequest)
    returns (GetRawTransactionResponse);
```

In this approach, the `GetRawTransactionRequest` will use the `oneof` keyword to specify the type of transaction, thus handling different transaction types within a single API call. The old API methods will be marked as deprecated.

### **Alternatives and current work-around**

Currently, we handle each transaction type with its specific RPC method, which leads to duplication and complexity. Another alternative could be to create separate handler functions within the same service method, but this would still result in some redundancy.

### **Additional context**

Consolidating the transaction APIs using the `oneof` keyword in Protocol Buffers will simplify the API, reduce redundancy, and make the codebase easier to maintain. This change would also provide more flexibility for future transaction types without needing additional RPC methods. Marking the old APIs as deprecated ensures backward compatibility during the transition.

**Comment by b00f** [comment]
How will the command line for `pactus-shell` look?
