### ISSUE TITLE
Enabling BloomFilter for store

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#1513]
We can enable a BloomFilter for the store and measure its performance. The BloomFilter can be configured as shown below:

```go
options := &opt.Options{
	Strict:      opt.DefaultStrict,
	Compression: opt.NoCompression,
	Filter:      filter.NewBloomFilter(10),
}
```

A benchmark report is required to evaluate the performance.

**Comment by Ja7ad** [comment]
> We can enable a BloomFilter for the store and measure its performance. The BloomFilter can be configured as shown below:
> 
> ```go
> options := &opt.Options{
> 	Strict:      opt.DefaultStrict,
> 	Compression: opt.NoCompression,
> 	Filter:      filter.NewBloomFilter(10),
> }
> ```
> 
> A benchmark report is required to evaluate the performance.

@themantre @b00f Write benchmark for read/write leveldb with or without this filter?

**Comment by b00f** [comment]
For both cases.
