### ISSUE TITLE
PIP-31: Consumptional Fee Model

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1540]
## Abstract

This issue proposes an enhancement to the Pactus fee model by incorporating dynamic fee adjustments based on network conditions and transaction demand. By introducing a consumption fee, we allow transactions with zero or low fees to be processed by the network, though these transactions may take longer than usual to be confirmed.

Proposal: https://pips.pactus.org/PIPs/pip-31
Discussion: https://github.com/pactus-project/PIPs/discussions/172

## Subtasks

- [x] #1541
- [x] #1542
- [x] #1543
- [x] #1544
- [x] #1545
- [x] #1573

**Comment by akbariandev** [comment]
@Ja7ad 
I think these 2 sub-tasks can merge into one.
` Update query calculating the fee based on consumption fee`
 And
` Update query calculating the fee based on consumption fee`
