### ISSUE TITLE
Validate fee in signed raw transactions in the transaction pool (tx_pool)

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1544]
When a new signed raw transaction is received in the tx_pool, the transaction needs to be validated before being broadcast to the network. Prior to broadcasting, the fee should be calculated, and if the fee is too low, the transaction should be rejected from the pool.

**Comment by akbariandev** [comment]
> When a new signed raw transaction is received in the tx_pool, the transaction needs to be validated before being broadcast to the network. Prior to broadcasting, the fee should be calculated, and if the fee is too low, the transaction should be rejected from the pool.

We have this validation in txpool. See this line
https://github.com/pactus-project/pactus/blob/693872b2aa17ced23bcbc50bc23d99a543fba149/txpool/txpool.go#L105

Also, the calculation of the fee is under #1542 task.
