### ISSUE TITLE
Display fee configuration in node information

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1546]
Display fee configuration from `config.toml` in node information.

```shell
/pactus/network/get_node_info
```

```json
{
  "moniker": "foobar",
...
  "fee": {
    "daily_limit": 250, // uint32
    "unit_price": 0.000005, // float64
    "fixed_fee": 0.01 // float64
  }
}
```

**Comment by Ja7ad** [comment]
@b00f We display consumption configuration or not planning?

**Comment by b00f** [comment]
I don't think we need to add in in gRPC. Please keep this issue open. We may add it in future.

**Comment by Ja7ad** [comment]
> I don't think we need to add in in gRPC. Please keep this issue open. We may add it in future.

Ok, remove this issue from parent issue.
