### ISSUE TITLE
Support gRPC method for Public key and Signature aggregation

### ISSUE THREAD

**Issue by Ja7ad** [pactus-project/pactus#1574]
## Describe the problem you'd like to have solved

In our crypto BLS library, we have public functions for handling `public key` and `signature` aggregation. Currently, we need an API to aggregate multiple public keys and signatures.

https://github.com/pactus-project/pactus/blob/9711f31c7713c8e18204b7dd8dad7f3a9ed0b459/crypto/bls/bls.go#L19

https://github.com/pactus-project/pactus/blob/9711f31c7713c8e18204b7dd8dad7f3a9ed0b459/crypto/bls/bls.go#L41

### Describe the ideal solution

We need two gRPC methods to accept multiple signatures or public keys and return an aggregated result in `util service`.

Suggested RPC method names:

```
rpc PublicKeyAggregation(req) returns (resp);
```

and

```
rpc SignatureAggregation(req) returns (resp);
```

**Comment by alidevjimmy** [comment]
What about Ed25519 aggregates?
Should we add two more methods for them or get signature and pub key type in request payload?

**Comment by Ja7ad** [comment]
> What about Ed25519 aggregates? Should we add two more methods for them or just get a signature or pub key type in the request payload?

@b00f

**Comment by b00f** [comment]
Just for BLS.
