### ISSUE TITLE
Read wallet password from the file

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#1610]
## Describe the problem you'd like to have solved

Currently, to start the node, the user must provide the wallet password as an argument to the `pactus-daemon` executable. This approach is particularly vulnerable, even if `pactus-daemon` is run as `sudo` by a non-root user. For example, if the server gets compromised, it is easy to retrieve the wallet password without needing the `sudo` password by using a command like:

```
ps -p $(pidof pactus-daemon) -o args
```

### Describe the ideal solution

To improve the security of the node, we can store the password in a file that is readable only by `sudo`. Then, the `pactus-daemon` process can be run with `sudo` and read the password from this file. This approach enhances security by protecting the wallet password with the `sudo` password.

**Comment by Ja7ad** [comment]
> ## Describe the problem you'd like to have solved
> Currently, to start the node, the user must provide the wallet password as an argument to the `pactus-daemon` executable. This approach is particularly vulnerable, even if `pactus-daemon` is run as `sudo` by a non-root user. For example, if the server gets compromised, it is easy to retrieve the wallet password without needing the `sudo` password by using a command like:
> 
> ```
> ps -p $(pidof pactus-daemon) -o args
> ```
> 
> ### Describe the ideal solution
> To improve the security of the node, we can store the password in a file that is readable only by `sudo`. Then, the `pactus-daemon` process can be run with `sudo` and read the password from this file. This approach enhances security by protecting the wallet password with the `sudo` password.

Currently we have switch from read password `--password foobar` for read file we define new switch `--password-from-file /home/user/password.txt`?
