### ISSUE TITLE
API for validator count 

### ISSUE THREAD

**Issue by nagarajmanjunath** [pactus-project/pactus#179]
Required API to get the total number of validators from the blockchain.

**Comment by b00f** [comment]
We should update `blockchain` method in gRPC and Capn'P to show the number of validators in the network.
We can have more details like current committee members and total stake, etc...

**Comment by b00f** [comment]
We can add this number inside blockchain API: https://github.com/zarbchain/zarb-go/blob/403f1c569ca1c220062f4e10e7d9e9c0f43b8e15/www/grpc/proto/zarb.proto#L80
