### ISSUE TITLE
How to send and recieve transaction?

### ISSUE THREAD

**Issue by khaninejad** [pactus-project/pactus#185]
Hi,

I need a method to implement a send and receive in the Zarb blockchain network using other clients rather than the core, but I couldn't find it on documents.
I would be happy if you assist me.

Thank you

**Comment by d4rk5h0t** [comment]
@khaninejad Thanks for bringing this up.

we do have gRPC, capnp, http(capnp) rpc endpoints to request a transaction or retrieve one
at the end of day you need a node running network to request these for you or a more unlikely run a node on phone itself and publish your transaction that way.
our `zarb` executable currently just generates the payload and lets you sign it we plan to add `server` flag to it so can publish it as well in the future.

our endpoints for sending or getting a transaction info are listed below i think you need to `generate payload -> serialize it -> sign it -> send it to a node` so there is not much we can do about it

```bash
rpc SendRawTransaction(SendRawTransactionRequest) returns(SendRawTransactionResponse)     { option (google.api.http).put = "/api/send_raw_transaction/{data}";};   #grpc endpoint for sending transaction()
rpc GetTransaction(TransactionRequest) returns (TransactionResponse)                      { option (google.api.http).get = "/api/tranaction/id/{id}";}            #grpc endpoint for retrieving one()
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/send_raw_transaction/{data}         #http endpoint for sending transaction
/transaction/id/{hash}                     #http endpoint for retrieving one
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
sendRawTransaction   @7 (rawTx: Data)                            -> (result :SendTransactionResult); #capnp endpoint for sending transaction
getTransaction       @2 (id: Data, verbosity: Int32)             -> (result :TransactionResult);         #capnp endpoint for retrieving one
```

but to generate payloads you need `.proto` file and [Data serialization](https://zarb.network/guide/learn-serialization.html) of [payload](https://github.com/zarbchain/zarb-go/blob/main/tx/tx.go#L24)  and [send transaction payload](https://github.com/zarbchain/zarb-go/blob/main/tx/payload/send.go#L10) we have a working [sample](https://github.com/zarbchain/zarb-go/blob/main/cmd/zarb/tx/send_tx.go#L115-L117) in go for it

let me know if you still need more clarification.
@b00f feel free to correct any part you see fit

**Comment by khaninejad** [comment]
but sending transaction raw data to API endpoint doesn't make this app decentralized or does it?

**Comment by khaninejad** [comment]
Would you please give a sample of how to fill these data? 
What Address, Number, Sequence, Balance stands for?

```
type Account struct {
   Address  Address `cbor:"1,keyasint"`
   Number   int     `cbor:"2,keyasint"`
   Sequence int     `cbor:"3,keyasint"`
   Balance  int64   `cbor:"4,keyasint"`
}

```

**Comment by d4rk5h0t** [comment]
> 
> 
> but sending transaction raw data to API endpoint doesn't make this app decentralized or does it?

well you need an entry point to the network the nodes running blockchain are the entry point if they accept to be



> 
> 
> Would you please give a sample of how to fill these data?
> What Address, Number, Sequence, Balance stands for?
> 
> ```
> type Account struct {
>    Address  Address `cbor:"1,keyasint"`
>    Number   int     `cbor:"2,keyasint"`
>    Sequence int     `cbor:"3,keyasint"`
>    Balance  int64   `cbor:"4,keyasint"`
> }
> ```

```bash
type Account struct {
   Address  Address `cbor:"1,keyasint"`              //Address of the Account "zrb1..." generated based on public key
   Number   int     `cbor:"2,keyasint"`                 //Number of the Account on the order seen on the network
   Sequence int     `cbor:"3,keyasint"`                 //Number of transaction account had as a mechanism to indecate loyalty and prevent reply and double spending 
   Balance  int64   `cbor:"4,keyasint"`                 //Accounts Current Balance how much zarb is stored in this account
}
```

**Comment by khaninejad** [comment]
> well you need an entry point to the network the nodes running blockchain are the entry point if they accept to be by allowing grpc or http servers be reachable for others
I know but consider it if the endpoints censored then clients won't be able to connect to the network. I am not an expert but I thought a network like DHT may be the solution for it. 

> you actually don't fill Account it's being generated based on your keys in the network and will be passed on you if you need to retrieve an account data we have an api on grpc and capnp will return information to you based on address of Account you may use those but you need to generate public,private key sets and generate address based on them before hand

It isn't clear, you know it seems that you're filing the sender data but what about the recipient? What are the benefits of sending the current balance of the sender?  and How to get "Number" & "Sequence" in the first place? what if my balance changed when after I signed the message?

**Comment by d4rk5h0t** [comment]
> 
> I know but consider it if the endpoints censored then clients won't be able to connect to the network. I am not an expert but I thought a network like DHT may be the solution for it.

`DHT ` is used in networks core the  nodes talk to each other to process transactions and other stuff but first you need to have a node publishing you transaction on network that why most of wallet's have there own RPC servers witch actully are nodes running network and allowing there app to talk to network thats why above i suggested running a node
@b00f  could you elaborate more


> It isn't clear, you know it seems that you're filing the sender data but what about the recipient?What are the benefits of sending the current balance of the sender?

I don't see where did you get this struct as payload the payloads for send process are as below
```go
type SendPayload struct {
	Sender   crypto.Address `cbor:"1,keyasint"`
	Receiver crypto.Address `cbor:"2,keyasint"`
	Amount   int64          `cbor:"3,keyasint"`
}
----------------------------------------------------------

type txData struct {
	Version   int
	Stamp     crypto.Hash
	Sequence  int
	Fee       int64
	Type      payload.Type
	Payload   payload.Payload
	Memo      string
	PublicKey *crypto.PublicKey
	Signature *crypto.Signature
}
```
which `SendPayload` will substitute `Payload`  of `txData` 

>How to get "Number" & "Sequence" in the first place?
well as i said you can query a node with the address and retrieve this data

>what if my balance changed when after I signed the message?
that's what consensus is for it will prevent you from double spending and fraudulent transactions will fail and will not persist on chain

**Comment by b00f** [comment]
@khaninejad 

Thanks for bringing this up

When you send a valid transaction to a node, it will broadcast into the network. 
All the validator will receive it and add it into the transaction pool. 
By creating a new block, proposer takes the valid transactions from the pool and add them into the block.

**Comment by b00f** [comment]
@khaninejad @d4rk5h0t 

I created this topic to discuss more about it: https://github.com/zarbchain/zarb-go/discussions/195

Please share your thoughts and ideas about it.

**Comment by khaninejad** [comment]
I managed to create this so far: 
http://cbor.me/?bytes=a9634665650a695369676e6174757265781968736a646866686a6173676466686173676466686a677364666853657175656e636518326756657273696f6e01675061796c6f616481a36852656365697665726d7a72626b6b64736b6a646b6a646653656e6465726a7a7262646a646a6a646466416d6f756e740a645479706501655374616d70657374616d70695075626c69634b65797635347335646634357364663435736434663573346466644d656d6f636d656d

But I have some question:
What is the meaning of "version of the transaction"
What is the "persisted Blocks hash" and how to get it?
How to get Account's transactions?
On the Cryptography page, you signed the keys with "Zarb", for the transaction section, what string and msg are required to sign the transaction?

**Comment by d4rk5h0t** [comment]
@khaninejad
> What is the meaning of "version of the transaction"

well as zarb grows and new features come along we may need to rethink the way transactions work and deprecate old implementations and let nodes support some set of transaction versions

>  What is the "persisted Blocks hash" and how to get it?

some blocks are persisted on blockchain some are pending and steel are appending transactions 
what i meant by that was you need to specify a block has (normally latest block) that is less than 24 hours old 
I've added it to [proto message](https://github.com/zarbchain/zarb-go/blob/main/www/grpc/proto/zarb.proto#L78)  so you can grab latest hash from there

>  How to get Account's transactions?

I Believe there is no API for this at moment in neither capnp nor gRPC. would you mind opening issue for it with the fields might be needed 👍

> On the Cryptography page, you signed the keys with "Zarb", for the transaction section, what string and msg are required to sign the transaction?

you need to sign transaction payload and append signature to it
samples are [here](https://github.com/zarbchain/zarb-go/blob/f36823683a069ff44878624ef986ce6df7e80667/tx/tx.go#L142) and [here](https://github.com/zarbchain/zarb-go/blob/main/tx/tx.go#L215) and [here](https://github.com/zarbchain/zarb-go/blob/ace78a1c75deda3765d2e9bf8b8aff650b9ab859/crypto/signer.go#L39)

**Comment by khaninejad** [comment]
What is the hash function for the Stamp, PublicKey and Signature?

**Comment by khaninejad** [comment]
I figured it out. it is a byte string

**Comment by khaninejad** [comment]
We have a sequence on API endpoint /account/address/ does it works?

**Comment by kehiy** [comment]
@b00f can we close this issue or turn it into a discussion?
