### ISSUE TITLE
firewall: Only accept messages from Validators

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#205]
Add new functionality to firewall to only accept messages from validators. 
We can check the initiator address to check if the message is initiated from a validator.
User can on/off this setting in firewall config file.

**Comment by kehiy** [comment]
how can we find out if a message bundle is from a validator?

**Comment by b00f** [comment]
@kehiy About the firewall we need to have a DEV-meeting to discuss about its internal behavior. It's good to postpone this issue until then

**Comment by kehiy** [comment]
@b00f that's ok
I wrote two functions, I will send a draft PR

**Comment by kehiy** [comment]
@b00f Should we work on this issue or close it?

Old issue....
