### ISSUE TITLE
Api for getting Account's transactions

### ISSUE THREAD

**Issue by khaninejad** [pactus-project/pactus#217]
### Describe the problem you'd like to have solved

Need an API to get the account's latest transaction, for sending a transaction or history of it.

**Comment by b00f** [comment]
We don't index transactions based on addresses. However we can use side projects (like block explorer) for indexing transactions based of sender and Receiver addresses.

**Comment by kehiy** [comment]
@b00f should we close this? we can add this sort of search support to an indexer project.

**Comment by b00f** [comment]
Yes, please close it. This is related to block explorer.
