### ISSUE TITLE
Migrating from mow.cli to cobra

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#288]
Currently we use [mow.cli](https://github.com/jawher/mow.cli) for CLI framework
[Cobra](https://github.com/spf13/cobra) is another popular CLI framework that has these features:

- Intelligent suggestions (app srver... did you mean app server?)
- Automatically generated shell autocomplete for your application (bash, zsh, fish, powershell)
- Automatically generated man pages for your application

It's proposed we move to cobra framework.

**Comment by kehiy** [comment]
@b00f @themantre 
I will start researching this and add the result as a comment here.
then we can start coding it.

**Comment by kehiy** [comment]
@b00f 
we have some options for `CLI` in Pactus.

the first way is to migrate the current `CLI` to Cobra and add our new features like interacting with the node.
and the second option is to make a new project like `Pactus-CLI` and provide all our expected options to interact with the Pactus node.

when we find out which one we are going to do, I can start fixing the issue.

**Comment by b00f** [comment]
For migrating from mow.cli to cobra we can start from [daemon](https://github.com/pactus-project/pactus/blob/main/cmd/daemon/main.go) first.

**Comment by kehiy** [comment]
ok, I will start to migrate the daemon code to Cobra for now.
but at the end, we also talk about a full CLI.

@b00f I will send a PR.
