### ISSUE TITLE
Copy to clipboard button

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#343]
Adding new button inside Entry and TextView widgets to let user copy the content to the clipboard:
![Screenshot from 2022-08-22 11-12-02](https://user-images.githubusercontent.com/8073510/185831367-7b720a69-80cc-446b-9a9a-38f1da79eaac.png)

**Comment by kehiy** [comment]
I think I can fix it, where are gui files located? I can't find them.

**Comment by b00f** [comment]
> where are gui files located? 

They are inside `cmd/gtk` folder

**Comment by kehiy** [comment]
> They are inside `cmd/gtk` folder

very nice, I will go to fix it ASAP.
