### ISSUE TITLE
Swagger doesn't accept hex 

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#377]
## Description

In order to use Swagger (OpenAPI) users should enter parameters as base64 format. Since data like block hash or transaction IDs are in hex (base16) format, this is troublesome.

### How To Reproduce

Check swagger APIs and try to get a block by hash. 

### What Happened

Input data should be in base64 format.

### Expected Behavior

It should accept base16 (hex) format for binary data.

**Comment by kehiy** [comment]
We need to remove `format` field for byte response or request fields.

example:
```json
        "blockHash": {
          "type": "string",
          "format": "byte"
        }
```

fixded:
```json
        "blockHash": {
          "type": "string"
        }
```


> the main issue is when we regenerate proto files with buf, all of this changes we reverted.

**Comment by kehiy** [comment]
more info:
https://swagger.io/docs/specification/data-models/data-types/

**Comment by b00f** [comment]
>  the main issue is when we regenerate proto files with buf, all of this changes we reverted.

We can do Post correction to update the json file. 
Using simple bash script. It is possible!


Good found @kehiy . Let's do it!

**Comment by b00f** [comment]
All Hashes should be same, better to display as hex.
