### ISSUE TITLE
Swagger doesn't work with multiple proto files

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#378]
## Description

After splitting proto files, swagger doesn't work and user should enter proto files manually to check the APIs.

### How To Reproduce

Compile the latest code and check swagger.

### What Happened

This error shows: `Failed to load API definition.`

### Workaround

Changing proto file in Swagger and then click "Explore".

**Comment by Ja7ad** [comment]
@b00f We can use trascoding standard of google API design guide.

In grpc gateway openapiv2 generators have opt allow_merge for merge swaggers.

```shell
protoc --proto_path=proto --openapiv2_out=allow_merge=true:api --openapiv2_opt use_go_templates=true proto/*.proto
```

**Comment by b00f** [comment]
@Ja7ad 
I wasn't aware of that. It seems like a good solution. Let's give it a try.

**Comment by Ja7ad** [comment]
> @Ja7ad I wasn't aware of that. It seems like a good solution. Let's give it a try.

This required to update all proto to support transcoding option for methods.
I do it.

**Comment by Ja7ad** [comment]
@b00f please assign to me dudu :)

**Comment by b00f** [comment]
@Ja7ad Did you find any solution for this issue?

**Comment by Ja7ad** [comment]
> @Ja7ad Did you find any solution for this issue?
> 

I use grpc gateway production ready for transcoding, support merge swagger and work it.

I do refactoring to fix this issue.
