### ISSUE TITLE
Stake Limit log for Users

### ISSUE THREAD

**Issue by HadiEsfahani** [pactus-project/pactus#410]
There's a Limit on how many (maximum) coins a node can stake as a validator. (based on the number of coins in the committee)
so beginner users should know how much they can stake (even if they want to bond their coins ASAP every time). and for beginners, I think this number (the limit) would be better to be accessible on GUI.

**Comment by b00f** [comment]
We have add information about committee in new GUI #411

**Comment by kehiy** [comment]
@b00f
We should close it, #411 is fixed and we have this information requested.
