### ISSUE TITLE
Replacing CapnP with gRPC for http package

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#418]
CapnP package is deprecated and should be removed. We need to replace CapnP with gRPC in http package:
https://github.com/pactus-project/pactus/blob/58c9045d1b0bc195ab91fc96e5aeb5fa9bb84e6e/www/http/server.go#L24

**Comment by braewoods** [comment]
Is help still wanted for this?

**Comment by b00f** [comment]
@braewoods Yes, Please.We have also Bounty for this issue. Check [here](https://app.bountysource.com/issues/113389756-replacing-capnp-with-grpc-for-http-package)
