### ISSUE TITLE
gui/flutter: Initializing the node wizard

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#421]
# Initializing the node wizard

The initializing wizard helps users to initialize the node. The initialize wizard has these pages:

## Initialize Mode page

User decides what he wants to:
- Create a new wallet
- Restore wallet from a mnemonic seed

It's better to add some icons for these options like [Monero](https://www.getmonero.org/downloads/).

### Current GUI:

![Screenshot](https://user-images.githubusercontent.com/8073510/200301718-6b0d0e67-764e-48df-9fde-581efcc9a96c.png)

###  Monero:

![Screenshot](https://user-images.githubusercontent.com/8073510/200301733-ce3a68be-b31a-41bb-89b6-14c2fdbf3383.png)

## Create a wallet page

In this page, a mnemonic seed will be generated for the user. To generate the mnemonic seed use [this package](https://github.com/dart-bitcoin/bip39). More info about BIP-39 can be found [here](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki)  

### Current GUI:

![Screenshot](https://user-images.githubusercontent.com/8073510/200301927-5d35b48c-8bf8-4ec5-821c-7b197f0856f6.png)

## Confirm seed page

In this page the user confirms the seed by retyping it again. The paste function should be disabled here and the user *has to* type the mnemonic seed again manually.

### Current GUI:

![Screenshot](https://user-images.githubusercontent.com/8073510/200302835-6985cc86-0d58-4bf7-b301-3dbe4e2afd15.png)

## Password page

In this page user can enter a password for the wallet. The password can be empty.

### Current GUI:

![Screenshot](https://user-images.githubusercontent.com/8073510/200303559-c1da367e-03da-43c2-bc7a-34ee1851cfb8.png)

###  Monero:

![Screenshot](https://user-images.githubusercontent.com/8073510/200303578-607c18f8-8b91-4914-9b4e-00fe323e0ea7.png)

## Summary page

Before the summary page, we should call `pactus-daemon` with `init` sub-command and initialize the folder. If  any error happens, we need to show it to the user, otherwise in the summary page we show the location of the working directory.

### Current GUI:

![Screenshot from 2022-11-07 19-55-04](https://user-images.githubusercontent.com/8073510/200304413-af4e3f52-822f-49b3-9028-7b479aece7fd.png)

###  Monero:

![Screenshot](https://user-images.githubusercontent.com/8073510/200304429-8a7798cc-acbe-4a6e-a975-a69fb00192c2.png)

## Restore wallet page 

If the user chose to restore the wallet, we ask him to enter the monotonic seed again.

###  Monero:

![Screenshot](https://user-images.githubusercontent.com/8073510/200307761-3c256a79-7551-4120-8f16-0c197225572a.png)

### How to let the user change the working directory?

Right now, the default location of the working directory is in the  `home_dir/pactus` folder. We have two options to let user to change the location of working directory:

1. Using command line argument:

The current GUI (and bitcoin-qt) uses this approach. If a user wants to use another location, he can run the GUI with an extra argument. like: `pactus-gui.exe -working-dir=C:\another-folder`

2. Adding location option in Create wallet page:

In this approach users can choose another folder for the working directory in the wizard.
There is a side effect here: we need to save this location somewhere as a global config (It's different per OS)

Let's choose the first approach for now. but we can change it in the future.

### How to show the Validator and Reward address in Summary pages?

The current GUI shows the validator and reward addresses in the summary page. To show these addresses in the new GUI, we need to get these addresses from the wallet:

```
pactus-wallet.exe address all
```

**Comment by b00f** [comment]
@meti-DeV

Here you can find some information about the GUI

**Comment by jwmdev** [comment]
@b00f  can you assign me this issue. I would like to develop it when I have time.

**Comment by b00f** [comment]
@jwmdev 

@MeTi-DeV has worked on this issue, primarily focusing on the GUI wallet. As far as I know, he has made significant implementation.

@MeTi-DeV I can't find the project you worked. Do you publish it?

**Comment by kehiy** [comment]
@b00f @jwmdev the GUI team is working on a new GUI for the Pactus node. we close this because we no longer need this UI and explanations.
