### ISSUE TITLE
http: Transactions are not shown in block page

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#428]
## Description

In the HTTP module, block page doesn't show the transactions inside the block. This probably because of:

 https://github.com/pactus-project/pactus/blob/7ddeba6beb143800e89044ac132ae3d57c02bbed/www/http/block.go#L45 

### How To Reproduce

To check the current issue you can visit this page: http://172.104.46.145:8080/block/hash/a0fa040561254691e466104c861331787714c68c740f45376f48009700a21dcd

In the local node, enable HTTP and check: http://localhost:8080/block/hash/<HASH>

### What Happened

The block doesn't have the information of each transactions.

### Expected Behavior

should show the all transactions inside the block

### Environment

- **Operation System:** Linux
- **Pactus Version:** Latest
- **Go Version** 1.19

**Comment by braewoods** [comment]
I have opened a PR that may solve this issue. I don't have access to a more complete data set to really know but it does appear to give more information than it did before. I tested all 3 values and the TRANSACTIONS variant seems to give the most information.
