### ISSUE TITLE
grpc: Payload type is `Unknown`

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#430]
## Description

Payload type for transactions is not set.  

### How To Reproduce

Call GetTransction API and check the payload type.

### What Happened

Payload type is "Unknown"

### Expected Behavior

Should be set properly.

### Extra

We need to add some tests case for payload type.

### Environment

- **Operation System:** Linux
- **Pactus Version:** Latest
- **Go Version** 1.19

**Comment by braewoods** [comment]
Did you forget to close this?

**Comment by b00f** [comment]
@braewoods Thanks for reminding.
