### ISSUE TITLE
parameter should be obtain from the node

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#434]
## Description

Right now, to calculate the fee we used the default parameters. The parameters should be obtained from the node.

### How To Reproduce

Send a transaction in TestNet with the Minimum Fee. For example set the amount to 0.0001.

### What Happened

The transaction fails, because the TestNet Parameters are not same as default parameters. Look at [calcfee](https://github.com/pactus-project/pactus/blob/6ed48725c9b98130816a1630a32d3eb2e380653d/wallet/wallet.go#L396) function.

### Expected Behavior

The parameters should be obtained from the node.

**Comment by b00f** [comment]
Fixing #590 will eliminate the need to know consensus parameters for fee calculation.

**Comment by b00f** [comment]
Yes, we can dude.
