### ISSUE TITLE
More information about the blockchain

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#438]
Adding more information to the BlockchainInfo gRPC API, including:

- Total number of accounts
- Total number of Validators
- Blockchain size in Bytes

**Comment by b00f** [comment]
How we can efficiently get the blockchain (or store) size roughly? We don't need the exact size.

**Comment by yenkhoon** [comment]
can we close this? it is already implemented.

**Comment by b00f** [comment]
@yenkhoon still we don't have solution for the blockchain size!

**Comment by b00f** [comment]
Any way to find the size of blockchain

**Comment by kehiy** [comment]
which one is possible?
I can do this

**Comment by b00f** [comment]
This issue is almost done. Only blockchain size is not implemented.

**Comment by kehiy** [comment]
yes, I meant the blockchain size
How we can calculate it?
from LevelDB or store...?

**Comment by b00f** [comment]
No idea, we are looking for a simple way to get the size of blockchain

**Comment by kehiy** [comment]
We decided to close this issue since we don't need blockchain size to be provided by gRPC.
