### ISSUE TITLE
Modify Withdrawal Transaction for Unbonded Validators

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#464]
## Description

The fee-less withdrawal transaction for unbonded validators may encourage spamming attacks on the network. To address this issue, modify the transaction to only allow the withdrawal of the entire stake amount from the validator's address to the designated receiver account. This would discourage spamming attacks without imposing additional fees for withdrawals, which may be beneficial for validators who have already paid fees for bonding.

### Expected Behavior

Withdrawal transaction only withdraws the entire stake amount from the validator's address to the designated receiver account, discouraging spamming attacks on the network.

**Comment by b00f** [comment]
@kehiy 

What do you think that we can remove [amount](https://github.com/pactus-project/pactus/blob/85f3063fa46ed4c892d1c7b8e7ec318e8cbe108d/types/tx/payload/withdraw.go#L15) from the withdraw transaction.

**Comment by kehiy** [comment]
@b00f 
that seems most `PoS` Blockchains have a TX fee or minimum unstake amount for `unbond` or `unstake` transactions.

for example:

Etherume: `Ensure you have a small amount of ETH to pay the Ethereum gas fee for your unstaking transaction.
The minimum unstake amount is 0.5 ETH.` 
Also: `For a flash unstake, you will pay a technical service — 0.5% of the unstacked amount.`

Solana needs about `0.000005 SOL` fee to unstake `1 SOL`

IMHO, keeping Withdrawal Transactions with fees makes sense.

**Comment by b00f** [comment]
> IMHO, keeping Withdrawal Transactions with fees makes sense.

Make sense. So we can close this PR and issue.
