### ISSUE TITLE
Node stopped syncing

### ISSUE THREAD

**Issue by stakeworks** [pactus-project/pactus#487]
## Description

Node stopped syncing last night at these lines:

ERRO[213444] error on sending bundle                       _sync="{☍ 19 ⛃ 50000 ⇈ 157159 ↑ 157158}" bundle="blocks-req{⚓ 109 157159:157159}" err="network error: no usable connection to peer" to=12D3KooWS7sqUFfSDAsDhW18PNwDTHndjsEdwTvukCCa5NQ4ZAY4
ERRO[219248] error on sending bundle                       _sync="{☍ 19 ⛃ 50000 ⇈ 157159 ↑ 157158}" bundle="blocks-req{⚓ 110 157159:157159}" err="network error: no usable connection to peer" to=12D3KooWD4wsex7J7zhRcbeq75oRWVonXyairkKVx1kBLKGYnEiW
ERRO[219251] error on adding a vote                        _consensus="{tpc1pa3p0sdm 157159/0/precommit}" err="duplicate vote" vote="{157159/0/prepare ⌘ 6CEEA1D78228 👤 tpc1pwdykak5}"
ERRO[219251] error on adding a vote                        _consensus="{tpc1pq6j8zd2 157159/0/precommit}" err="duplicate vote" vote="{157159/0/prepare ⌘ 6CEEA1D78228 👤 tpc1pwdykak5}"

After restart node started syncing again.

### Environment

- **Operation System: ** Ubuntu 20.04.6 LTS
- **Pactus Version: **  0.10.0-beta+c2fae1df
- **Go Version** go1.19.3 linux/amd64

**Comment by b00f** [comment]
It's fixed on #486 

@stakeworks  Thanks for reporting. Let's keep this issue open until we ensure that it has been fully tested in the testing network. 
However, I have tested it using [TLA+](https://lamport.azurewebsites.net/tla/tla.html) and TLC checker with more than  1 million distinct states.
