### ISSUE TITLE
Adding MinimumStake to the consensus parameters

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#501]
## Describe the problem you'd like to have solved

Adding `MinimumStake` to the consensus parameters prevents creating dummy validators, specially in the Mainnet.
Spammers might create thousands of validators with small stakes. This has no effect on the consensus mechanism or the sortition algorithm.

### Describe the ideal solution

Adding a new field in the [consensus parameters](https://github.com/pactus-project/pactus/blob/main/types/param/param.go) for `MinimumStake`. The default value can set to 1 PAC coin.

**Comment by kehiy** [comment]
is 1 PAC make sense?
because its still easy to make dummy validators!?
