### ISSUE TITLE
gRPC: Adding new API for GetAccountByNumber

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#505]
The `GetAccountByNumber` API would be beneficial in scenarios where user need to fetch account details by account number instead of address.

This API is similar to [GetValidatorByNumber](https://github.com/pactus-project/pactus/blob/fd4204a9036222efe84807559aa9342ca752f384/www/grpc/blockchain.go#L175) and can follow the same way to implement.

**Comment by IoannisFlo** [comment]
hey @Ja7ad, you'll want to include `/claim #505` in the body of your PR (ex. right after `Fixed #505`) 👻
