### ISSUE TITLE
Warn Users When Attempting to Bond to a Reward Address

### ISSUE THREAD

**Issue by aboka2k** [pactus-project/pactus#510]
Hi! I would like to propose a new feature that helps users avoid accidentally bonding to a reward address. Currently, when users bond to a reward address, they receive no rewards, and it takes 21 days for them to unbond. To prevent this disadvantageous situation, I suggest implementing a warning and confirmation message whenever a user attempts to bond to a reward address. This will help users make informed decisions and avoid potential loss of time & rewards.

regards,

**Comment by b00f** [comment]
> I suggest implementing a warning and confirmation message whenever a user attempts to bond to a reward address

In the Bond transaction dialog in the GUI app, we don't list reward addresses. However, users might mistakenly set a reward address in the CLI. I am still unsure whether adding this check in the code is necessary. Let's keep this issue open and see if we receive more feedback from users.

**Comment by aboka2k** [comment]
Thank you for considering the proposal and providing your perspective. I understand that implementing this feature may not be an immediate priority compared to other important tasks at hand. However, I still believe that having a safety mechanism in place, even if it's not frequently utilized, can provide peace of mind and protect users from unintended consequences.

I kindly request that you consider making this improvement when your team has the time and resources available in the future, even if there is no immediate response or demand from other users. It's always beneficial to proactively enhance user experience and mitigate potential risks.

**Comment by b00f** [comment]
@aboka2k, I understand your concern. However, we need to be caution when adding even a single line of code. That's why I insist on keeping the issue open and gathering more feedback. Additionally, please consider that issue #494 might potentially change the way we define validator and reward addresses. 

Thank you for your understanding, and I appreciate your willingness to consider different perspectives. Let's continue to gather feedback and evaluate the best approach for addressing this issue.

**Comment by kehiy** [comment]
I think it will be fixed after pip-8
- https://github.com/pactus-project/PIPs/discussions/28

**Comment by b00f** [comment]
@aboka2k The issue has been resolved in this Pull Request (PR). Now, if a user sends a bond transaction to any account, they will encounter an error. Thank you for bringing this to our attention, and for your continued support.
