### ISSUE TITLE
Updating LRU cache to version2 

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#514]
We use [golang-lru](https://github.com/hashicorp/golang-lru) library to [cache](https://github.com/pactus-project/pactus/blob/f550c7949615029c5ce43fb06dc5289c4c7ffb5c/sync/cache/cache.go#L31) blocks and certificates in the sync module of our project called Pactus.

The purpose of LRU caching is to store frequently accessed items in a cache so that we can retrieve them quickly. When the cache becomes full, the least recently used items are removed to make space for new items.

Here's how it works:

When a node starts syncing, it receives blocks and block certificates from other nodes, which may not arrive in order. For example, we might receive block 100 before block 10. To handle this, we store all the blocks and certificates in the LRU cache. We use the height of the block or certificate as the key, making it easy to retrieve and commit them.

There are some improvements that can be made:

1- We can update the golang-lru package from version 1 to version 2, which supports generics. This update would allow us to avoid unnecessary type casting.
2- Instead of using a single LRU cache, we can define two separate caches: one for blocks and another for certificates.
3- For the key, we can simply use the height of the block or certificate.

**Comment by Ja7ad** [comment]
> We use [golang-lru](https://github.com/hashicorp/golang-lru) library to [cache](https://github.com/pactus-project/pactus/blob/f550c7949615029c5ce43fb06dc5289c4c7ffb5c/sync/cache/cache.go#L31) blocks and certificates in the sync module of our project called Pactus.
> 
> The purpose of LRU caching is to store frequently accessed items in a cache so that we can retrieve them quickly. When the cache becomes full, the least recently used items are removed to make space for new items.
> 
> Here's how it works:
> 
> When a node starts syncing, it receives blocks and block certificates from other nodes, which may not arrive in order. For example, we might receive block 100 before block 10. To handle this, we store all the blocks and certificates in the LRU cache. We use the height of the block or certificate as the key, making it easy to retrieve and commit them.
> 
> There are some improvements that can be made:
> 
> 1- We can update the golang-lru package from version 1 to version 2, which supports generics. This update would allow us to avoid unnecessary type casting. 2- Instead of using a single LRU cache, we can define two separate caches: one for blocks and another for certificates. 3- For the key, we can simply use the height of the block or certificate.

**Updating the golang-lru package to version 2:** By updating to version 2, you can take advantage of Go's generics feature, introduced in Go 1.18. This will make your code cleaner and more type-safe by avoiding unnecessary type casting. If you are using Go 1.18 or newer, this update is recommended.

**Using separate caches for blocks and certificates:** Separating the caches for blocks and certificates can improve the maintainability of your code and make it easier to reason about the cache behavior for each data type. This separation might also allow for better tuning of cache sizes and eviction policies for each cache, if needed.

**Using the height as the key:** Using the height of the block or certificate as the key is straightforward and efficient. It allows for easy retrieval and commit operations. However, it is essential to ensure that heights are unique and that there are no collisions between block heights and certificate heights in their respective caches.

Overall, these improvements can make your code more efficient, maintainable, and easier to understand. It's crucial to consider the trade-offs and the impact of these changes on your project's overall performance and resource usage to make the most informed decision.

**Comment by b00f** [comment]
> A benchmark test is necessary before updating to version 2, because generics can be more costs sometimes.

Absolutely! It's really good idea to do a benchmarking here.

**Comment by kehiy** [comment]
how can we do the benchmark?

**Comment by b00f** [comment]
> how can we do the benchmark?

@Ja7ad how to do bench marking? 

The main benefit is removing unnecessary type castings.

**Comment by Ja7ad** [comment]
@b00f 

I write benchmark for V1 and V2 and base on result V2 is low cost.

```shell
goos: linux
goarch: amd64
pkg: github.com/pactus-project/pactus/sync/cache
cpu: AMD Ryzen 3 PRO 2300U w/ Radeon Vega Mobile Gfx
BenchmarkCacheV1
BenchmarkCacheV1-4   	  949814	      1371 ns/op	     413 B/op	       9 allocs/op
BenchmarkCacheV2
BenchmarkCacheV2-4   	 1460439	       849.5 ns/op	     278 B/op	       5 allocs/op
PASS
```

**Comment by b00f** [comment]
Interesting. So we have strong reason to move to v2.

**Comment by sadaghiani** [comment]
Hi, I will do it

**Comment by sadaghiani** [comment]
- Because I just got to know Pactus, I tried to review the codes.

- I did the 3 above mentioned items -> https://github.com/pactus-project/pactus/issues/514#issue-1760333878 and I have a question about the size of the cache ?!
I considered this size for each cache [`func NewCache(size int) (*Cache, error) {...`](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/sync/cache/cache.go#L34) Because there is no need to specify the configuration for each. Of course, if the block and certificate size (Len) are always the same. Now return the [length](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/sync/cache/cache.go#L78) of the block cache? Enough ? Do you agree?

- I also changed [this function](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/sync/cache/cache.go#L45) from Get to Contains. Because in github.com/hashicorp/golang-lru/v2, if we use Get, we change the cache state, but we just need to check that it is in the cache? In the benchmark, the cost is almost half.

**Comment by Ja7ad** [comment]
> - Because I just got to know Pactus, I tried to review the codes.
> 
> - I did the 3 above mentioned items -> https://github.com/pactus-project/pactus/issues/514#issue-1760333878 and I have a question about the size of the cache ?!
> I considered this size for each cache [`func NewCache(size int) (*Cache, error) {...`](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/sync/cache/cache.go#L34) Because there is no need to specify the configuration for each. Of course, if the block and certificate size (Len) are always the same. Now return the [length](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/sync/cache/cache.go#L78) of the block cache? Enough ? Do you agree?
> 
> - I also changed [this function](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/sync/cache/cache.go#L45) from Get to Contains. Because in github.com/hashicorp/golang-lru/v2, if we use Get, we change the cache state, but we just need to check that it is in the cache? In the benchmark, the cost is almost half.
> 
> 

@b00f

**Comment by b00f** [comment]
@sadaghiani 

>Now return the [length](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/sync/cache/cache.go#L78) of the block cache? Enough ? Do you agree?

For a cache, `Len` is probably only important for diagnostic purposes, such as logging. The cache's owner won't necessarily need to know how much of the cache has been used (length).

In this case, we have several possible solutions:

1. Remove `Len`. However, can we be certain that we won't need this property in the future, even for debugging? It's difficult to say for sure.
2. Modify `Len` to only return the number of items in the Block cache. This raises the immediate question of why we chose Blocks and not Certificates. Therefore, this solution is not consistent.
3. `Len` returns the maximum value between the two lengths (blocks and certificates).
4. Modify `Len` to return both lengths, for both blocks and certificates. However, this exposes the internal behavior of the cache to the outside world.

Solution number 3 seems like a reasonable approach. What do you think @sadaghiani ?

> I also changed [this function](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/sync/cache/cache.go#L45) from Get to Contains.

You did the right thing.

**Comment by sadaghiani** [comment]
I had thought of the third solution but didn't like if statement for check maximum length, also the second is not consistent approach.

we do third @b00f
