### ISSUE TITLE
Address validation for the network module

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#524]
## Description

We currently do not validate the [network addresses](https://docs.libp2p.io/concepts/fundamentals/addressing/) in the config file. So, if a user enters an incorrect address, the node won't start (an incorrect listen address can even cause a system crash). We need to ensure all addresses, both relay and listen addresses, are valid in the [SanityCheck](https://github.com/pactus-project/pactus/blob/01d155b09c7db3ab279668f7973f7ebc9194cc89/network/config.go#L65) function. 

### How To Reproduce

1. Open the config file.
2. Change the listen addresses and relay addresses to an incorrect string.

### What Happened

The node didn't start. It may also cause a system crash.

### Expected Behavior

Should return invalid address error before starting the node.
Write tests for the invalid addressess.

**Comment by kehiy** [comment]
check: #565

**Comment by kehiy** [comment]
@b00f we can close it now!
