### ISSUE TITLE
Pre-calculate the validator addresses 

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#525]
Currently, in the state module, we maintain a list of validators' private keys as [signers](https://github.com/pactus-project/pactus/blob/01d155b09c7db3ab279668f7973f7ebc9194cc89/state/state.go#L34), which is used to evaluate the sortition at each height. For each validator, we have a private key, and for each private key, we evaluate the sortition.

To [evaluate the sortition](https://github.com/pactus-project/pactus/blob/01d155b09c7db3ab279668f7973f7ebc9194cc89/state/state.go#L459), we need the validator's address. However, calculating the address from the signer (or private key) involves these steps: Private Key -> Public Key -> Address.

This process can be optimized. Instead of recalculating the address each time, we propose to pre-calculate these addresses and store them in a `signersMap`: `map[crypto.Address]crypto.Signer`.

By doing so, we can directly use the pre-calculated address from the key in the map during iteration, making the process more efficient.

**Comment by kehiy** [comment]
where we should add the `signersMap`?

**Comment by b00f** [comment]
An out of box idea:

Signer has per-calculated address, so this issue can be closed.
