### ISSUE TITLE
gRPC: Missing GetAccountByNumber API in SwaggerUI

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#527]
## Description

SwaggerUI is not showing the `GetAccountByNumber` API. 
This happened because it wasn't added to the [grpc-gateway.config.yaml](https://github.com/pactus-project/pactus/blob/main/www/grpc/grpc-gateway.config.yaml).

Please double check if we have missed any other APIs there.

Related #505

**Comment by kehiy** [comment]
please check the #564

**Comment by kehiy** [comment]
@b00f we can close it now i think

**Comment by b00f** [comment]
Closed, @kehiy Thanks
