### ISSUE TITLE
HTTP: Add Missing APIs for Account and Validator By Number

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#528]
## Describe the problem you'd like to have solved

The HTTP module in Pactus works like a simple HTTP server to provide some information about the node. 
You can think of it as a very basic block explorer.

Currently, there are two APIs missing in the HTTP module: `GetAccountByNumber` and `GetValidatorByNumber`.

### Describe the ideal solution

The first thing you need to do is to add these routes:

```
/account/number/{number}
/validator/number/{number}
```
Then add the `GetAccountByNumberHandler` handlers inside [account.go](https://github.com/pactus-project/pactus/blob/main/www/http/account.go) and  `GetValidatorByNumberHandler` inside [validator.go](https://github.com/pactus-project/pactus/blob/main/www/http/validator.go).

Please don't forget to write tests for both APIs.

**Comment by kehiy** [comment]
hello.
I'll start working on this issue!

**Comment by kehiy** [comment]
chek #541

**Comment by kehiy** [comment]
fixed in: #549

**Comment by kehiy** [comment]
@b00f should we close this issue?

**Comment by b00f** [comment]
Yes, we can close it now. Thanks @kehiy
