### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by kehiy** [pactus-project/pactus#530]
https://github.com/pactus-project/pactus/blob/main/types/genesis/testnet.json

this file link in the pactud documents https://pactus.org/learn/blockchain/genesis/
is not found

**Comment by Ja7ad** [comment]
> https://github.com/pactus-project/pactus/blob/main/types/genesis/testnet.json
> 
> this file link in the pactud documents https://pactus.org/learn/blockchain/genesis/ is not found

you can check in https://github.com/pactus-project/pactus/blob/main/genesis/testnet.json
