### ISSUE TITLE
Supporting snap for Linux

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#545]
## Describe the problem you'd like to have solved

Some users are having difficulties running Pactus on Linux, especially on Ubuntu 20.04. 
This is because GLIBC_2.32 (intended for Ubuntu 22.04) and higher cannot be installed on Ubuntu 20.04.

### Describe the ideal solution

We should consider packaging Pactus using Snap. 
This approach will enable users with different distros to run Pactus without worrying about missing dependencies.

### Alternatives and current work-around

The only workaround currently available is to compile Pactus directly on the target machine.

**Comment by Ja7ad** [comment]
@b00f we need to support deb and rpm too.

**Comment by b00f** [comment]
Here you can find an example of Bitcoin packaging using snap: https://github.com/bitcoin-core/packaging

**Comment by laosiji-io** [comment]
This can only be compiled by the user themselves.
Don't worry too much, we just need to tell them how to compile it.

**Comment by b00f** [comment]
@laosiji-io I am afraid to say that we are worried. We want to make it easy for users to run Pactus. 
We can't simply say "go and compile." 
We should support a variety of operating systems and packaging.

**Comment by laosiji-io** [comment]
I am currently trying to use SnapCraft to create installation packages.
But there are also some issues that cannot load dependencies like GLIBC_2.29.
Different systems encounter different isssues as well.

**Comment by b00f** [comment]
I am confident that we can overcome these difficulties.

**Comment by laosiji-io** [comment]
At present, the snap installation package can be successfully built locally.
The next step is to publish to the Snap Store and implement automatic build.

**Comment by kehiy** [comment]
Any updates on this PR? I can see other projects providing their releases on these repos but they mentioned that this is a community version and unofficial, such as IPFS Kubo implementation. All repos have them but from the community.

What do you think?

**Comment by b00f** [comment]
I believe AppImage is sufficient for now, as it works with most Linux distributions. There's no need for Snap at this moment.
