### ISSUE TITLE
Garbage collection for peerset

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#546]
## Describe the problem you'd like to have solved

Once a node joins the network, it sends `hello` [message](https://github.com/pactus-project/pactus/blob/a75fe24372bd3cd35d6a6c0d725f26e84a1c0357/sync/bundle/message/hello.go#L20) and announce its peer ID and consensus keys. 
However, we currently don't have a mechanism to remove a node from the [peer list](https://github.com/pactus-project/pactus/blob/a75fe24372bd3cd35d6a6c0d725f26e84a1c0357/sync/peerset/peer_set.go#L19C23-L19C24) once it goes offline.

### Describe the ideal solution

We need to establish a mechanism for garbage collection. A garbage node should have a clear definition.
A node can be considered "garbage" if we haven't heard from it in the last few hours.
Each peer has a property named [last_seen](https://github.com/pactus-project/pactus/blob/a75fe24372bd3cd35d6a6c0d725f26e84a1c0357/sync/peerset/peer.go#L24) that gets updated each time we receive data from that node.
We can use this property to calculate how long a node has been offline. 
If a node has been offline for more than a day, we should remove it from the peer list. 
The garbage collector check could be scheduled to run daily

### Alternatives and current work-around

Currently, the only workaround is to restart the node.

**Comment by b00f** [comment]
> how can we set scheduled function in pactus?

Scheduled routine can be implemented using [timer](https://gobyexample.com/timers). Probably we need to create a [goroutine](https://go.dev/tour/concurrency/1). Something like:

```go
func (ps *PeerSet) garbageCollector(ctx context.Context, timeout time.duration) {
	timer := time.NewTimer(duration)
	for {
		select {
		case <-timer.C:
			// loop over all peers and find the offline ones
			timer.Reset(duration)
		case <-ctx.Done():
			timer.Stop()
		}
	}
}
```

The best place for this routine is in `PeerSet`, the problem is we don't have the `context` here. So we need slightly modify the `NewPeerSet` to accepts the context from sync module:

```go
func NewPeerSet(ctx context.Context, sessionTimeout time.Duration) *PeerSet {
   clearanceTimeut := time.Hour * 24
   go ps.garbageCollector(ctx, clearanceTimeut)

}
```

Another option is defining this routine inside `sync` . Not a good idea. Because this is not `sync` task to clear the offline peers in `PeerSet`. It looks `PeerSet` is a better place. 

>  and wcich parts a person need to read for done this?

Most of the link in this issue are a good place to start.

**Comment by kehiy** [comment]
> 



> > how can we set scheduled function in pactus?
> 
> Scheduled routine can be implemented using [timer](https://gobyexample.com/timers). Probably we need to create a [goroutine](https://go.dev/tour/concurrency/1). Something like:
> 
> ```go
> func (ps *PeerSet) garbageCollector(ctx context.Context, timeout time.duration) {
> 	timer := time.NewTimer(duration)
> 	for {
> 		select {
> 		case <-timer.C:
> 			// loop over all peers and find the offline ones
> 			timer.Reset(duration)
> 		case <-ctx.Done():
> 			timer.Stop()
> 		}
> 	}
> }
> ```
> 
> The best place for this routine is in `PeerSet`, the problem is we don't have the `context` here. So we need slightly modify the `NewPeerSet` to accepts the context from sync module:
> 
> ```go
> func NewPeerSet(ctx context.Context, sessionTimeout time.Duration) *PeerSet {
>    clearanceTimeut := time.Hour * 24
>    go ps.garbageCollector(ctx, clearanceTimeut)
> 
> }
> ```
> 
> Another option is defining this routine inside `sync` . Not a good idea. Because this is not `sync` task to clear the offline peers in `PeerSet`. It looks `PeerSet` is a better place.
> 
> > and wcich parts a person need to read for done this?
> 
> Most of the link in this issue are a good place to start.

it seems a little complex
whats your opinion? can I start to solve this issue?

**Comment by b00f** [comment]
> it seems a little complex

It might looks like. But it is easy.

>  whats your opinion? can I start to solve this issue?

Follow your path. I can help you if you have any quesion

**Comment by kehiy** [comment]
> > it seems a little complex
> 
> It might looks like. But it is easy.
> 
> > whats your opinion? can I start to solve this issue?
> 
> Follow your path. I can help you if you have any question

that's ok, i'm gonna work on this issue...

**Comment by kehiy** [comment]
@b00f From what we discussed we don't need to garbage collect peers data, also we need to keep them when a node is off.
I think we can close this isse now.

**Comment by b00f** [comment]
Let's close it for now. But keep an eye on this issue on Testnet-2.
