### ISSUE TITLE
Resource manager for LibP2P

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#548]
## Describe the problem you'd like to have solved

LibP2p provides an interesting feature called the [resource manager](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/resource-manager/README.md), which allows us to manage resources and monitor network activity. To have a better understanding of network activity, we should be able to utilize the resource manager and monitor the node's activity.

### Describe the ideal solution

Resource manger can be used with Prometheus and Grafena. (How?) 

### Alternatives and current work-around

Currently, we can use the existing `sync` package to obtain some statistics about network usage. 
However, this only provides information about data received or sent at the application layer. 

Related to #529

**Comment by kehiy** [comment]
@b00f and this I think.

**Comment by b00f** [comment]
Let's test it then we can close it

**Comment by kehiy** [comment]
@b00f Know we can test and check the resource manager by following metrics document.
I already testes it with my node, everything works.
can we close it?

**Comment by b00f** [comment]
@kehiy Closed . Thanks for reminding.
