### ISSUE TITLE
mux packcage archive mode

### ISSUE THREAD

**Issue by kehiy** [pactus-project/pactus#550]
## Description
in HTTP part of pactus its use gorilla/mux the gorilla packages are in archive mode since end of 2022!
I think we should refactor the codes and use another package or maybe just use the pure go.

that's because gorilla wasn't update with new go versions and it can be danger.

**Comment by b00f** [comment]
It's good idea. Which package do you recommend to use?

**Comment by kehiy** [comment]
in order that's good to use lightweight package I think echo is good also chi is good too.
the pure net/http are still the best choice...

**Comment by Ja7ad** [comment]
> @Ja7ad do you have any idea?
> 

We need trascoding protocol buffers

https://cloud.google.com/transcoder/docs

**Comment by b00f** [comment]
Usually google's library are too heavy. We need something light.

**Comment by b00f** [comment]
@kehiy Do you have any comparisons between the current libraries?

**Comment by Ja7ad** [comment]
> Usually google's library are too heavy. We need something light.

We need to all, just http annotation for transcoding

**Comment by Ja7ad** [comment]
> > @kehiy Do you have any comparisons between the current libraries?
> 
> In general, Echo is one of the most suitable pkg after Mux
> But for comparison, I can do a more detailed research

Better we don't use a framework.

**Comment by kehiy** [comment]
> > > @kehiy Do you have any comparisons between the current libraries?
> > 
> > 
> > In general, Echo is one of the most suitable pkg after Mux
> > But for comparison, I can do a more detailed research
> 
> Better we don't use a framework.

i'm agree with you!
The best way is to use something that does not have security problems with its updates.
I do not have complete information about what you introduced
I came across 403 to read its documentation
But if it has such conditions, it can be a good case instead of Mux

**Comment by b00f** [comment]
Guys, this issue has very low priority. Please focus on other issues we have right now,

**Comment by kehiy** [comment]
> Guys, this issue has very low priority. Please focus on other issues we have right now,

that's ok
probably i'm going to fix garbage collector issue...

**Comment by kehiy** [comment]
@b00f @Ja7ad 
https://github.com/gorilla/mux are not in archive mode and it found new maintainers, so we can just update mux with new updates!

I'm going to close this issue.

**Comment by b00f** [comment]
Good news for us.
