### ISSUE TITLE
Documents in github

### ISSUE THREAD

**Issue by kehiy** [pactus-project/pactus#572]
## Describe the problem you'd like to have solved
I think we need to add more detail in GitHub README.md for `pactus`
and explain a little more about it for new commer developers in `pactus`
that's easier instead than directing them to the website before anything

adding this part and fixing this is not too hard and doesn't take much time I think, but it can help so much.

**Comment by b00f** [comment]
Did you check the [CONTRIBUTING.md](https://github.com/pactus-project/pactus/blob/main/CONTRIBUTING.md) and [install.md](https://github.com/pactus-project/pactus/blob/main/docs/install.md)

**Comment by kehiy** [comment]
I also check and read them.
but I thought having more detail in `README.md` can help.
how ever, if it's unnecessary we can close it.

**Comment by b00f** [comment]
For more documents, we can use the `docs` folder. 
Add everything in `README` is not a good idea.
