### ISSUE TITLE
More and better metrics

### ISSUE THREAD

**Issue by kehiy** [pactus-project/pactus#578]
## Describe the problem you'd like to have solved

we can use some ways to provide more and better metrics in Pactus.
one way is to provide all the network data in a data format for monitoring apps and also another endpoint for getting data as JSON.

### Describe the ideal solution

first of all, we need two endpoints, one for monitoring tools and one for JSON.
`Prometheus data format` is a good way for the first one, this is an example:
```Prometheus
# HELP http_requests_total Total number of HTTP requests
# TYPE http_requests_total counter
http_requests_total{method="GET", endpoint="/api/users", status_code="200"} 500
http_requests_total{method="POST", endpoint="/api/posts", status_code="201"} 200
http_requests_total{method="GET", endpoint="/api/comments", status_code="404"} 50
```
this a the Prometheus data format example.

and for JSON simply we need an endpoint to provide all network data with one call.

### Alternatives and current work-around

for now, we don't have any endpoint to get data for monitoring tools
and also we don't have a JSON endpoint to get all data with one call.

now we just have a JSON endpoint for specific data.

**Comment by kehiy** [comment]
also, I should mention that it helps us very much to make network usage efficient and analyze it.
#571

**Comment by amirvalhalla** [comment]
related topic about `libp2p resource manager` and using Prometheus : [libp2p resource manager](https://github.com/libp2p/go-libp2p/tree/master/p2p/host/resource-manager)

**Comment by amirvalhalla** [comment]
@b00f 
@kehiy 
I've started to working on this issue

**Comment by kehiy** [comment]
> @b00f @kehiy I've started to working on this issue

very nice, keep in mind if you can make this in a way that normal users can use it, do it!
