### ISSUE TITLE
gzip usage in network

### ISSUE THREAD

**Issue by kehiy** [pactus-project/pactus#586]
## Description

using gzip for compression messages in the network, *doesn't make sense for all messages!*
gzip works on **repetitive patterns or text** that means for some messages that don't have repetitive patterns the gzip going to go make everything the opposite.

### How To Reproduce

make a default struct from some message in the `Pactus` protocol, then try to compress it with `gzip`.
you see most of the time the result is the opposite.

### Extra

we have 2 ways to fix this issue:
* stop using gzip at all
* use it after checking the data and make sure compression for it makes sense (not efficient)

### related to
- #571 
** This is the first step for reducing network usage.

### Environment

- **Operation System: Linux**
- **Pactus Version:0.13**
- **Go Version:1.21**

**Comment by b00f** [comment]
Regarding the compression of network packets:

1- Most of the data we transmit over the network consists of random elements like hashes or signatures. Compression algorithms usually don't significantly reduce the size of this kind of data. However, having the configurable option for compression data would be beneficial.

2- The [bundle struct](https://github.com/pactus-project/pactus/blob/236b5cac9e124a3baea8162478ae01c958e2f607/sync/bundle/bundle.go#L23) supports compression. When a bundle is compressed, the [compression flag](https://github.com/pactus-project/pactus/blob/236b5cac9e124a3baea8162478ae01c958e2f607/sync/bundle/bundle.go#L68) is set. This allows the receiver to know that it should decompress the data.

3- Currently, we only compress the [block_response](https://github.com/pactus-project/pactus/blob/main/sync/bundle/message/blocks_response.go) message (that is the biggest message). We have [a test](https://github.com/pactus-project/pactus/blob/236b5cac9e124a3baea8162478ae01c958e2f607/sync/bundle/bundle_test.go#L33) for that. Please feel free to check the test and review the results.

4- LibP2P doesn't support [transport compression](https://github.com/libp2p/specs/issues/485) at this time.

**Comment by kehiy** [comment]
@b00f 
I worked more on Gzip yesterday.
I found something and I think the badest thing we can do is  compress the [block_response](https://github.com/pactus-project/pactus/blob/main/sync/bundle/message/blocks_response.go)
I will work on this and provide the result and benchmarks in a PR.
