### ISSUE TITLE
Replacing Logrus with zerolog

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#587]
Currently, [Logrus](https://github.com/sirupsen/logrus) is being used for logging. When certain levels like Trace are off, program still evaluates these log messages, leading to potential performance issues. For example:

```go
logger.Trace("Processing took: ", complexFunction())
```

In this case, `complexFunction()` is evaluated even if Trace level logging is off, adding unnecessary overhead.
An alternative approach is to use the [zerolog](https://github.com/rs/zerolog) library which provides more control over logging overhead:

```go
log.Trace().Msg("this message may not be logged depending on level", complexFunction())
```

In this case, `complexFunction()` would only be evaluated when the trace log level is enabled, which could improve performance by reducing unnecessary computations and log object creation.

For a performance comparison between zerolog and logrus, check out this [benchmark](http://hackemist.com/logbench/).

**Comment by Ja7ad** [comment]
I think zap is better

https://github.com/uber-go/zap

**Comment by Ja7ad** [comment]
> @Ja7ad 
> 
> Based on the [benchmark](http://hackemist.com/logbench/) zerolog has better performance. Why do you think zap is better?

Zap has the best benchmark and is customizable

**Comment by kehiy** [comment]
@b00f @Ja7ad 
I want start working on this issue
zap or zerolog?
wich one should I use?

**Comment by Ja7ad** [comment]
> @b00f @Ja7ad 
> I want start working on this issue
> zap or zerolog?
> wich one should I use?

Zap, that's extensible and customizable.

**Comment by kehiy** [comment]
> Zap, that's extensible and customizable.

thank you, I will replace it with zap.

**Comment by b00f** [comment]
No, please let's discuss first. @Ja7ad we need comparison.

**Comment by kehiy** [comment]
> Please wait. Don't rush. Let's discuss first. @Ja7ad we need comparison.
 that's ok, when we find the best one, I will send a new PR.

**Comment by b00f** [comment]
@kehiy, could you please Google it and see if we can find a comparison for these two loggers?

**Comment by Ja7ad** [comment]
> @kehiy, could you please Google it and see if we can find a comparison for these two loggers? 

Zap is extensible and customizable, we can use it for multiple cores at the same time (file, console, json and etc)

**Comment by kehiy** [comment]
@b00f @Ja7ad 
[this](https://www.crowdstrike.com/blog/logging-with-go/#:~:text=Zerolog%20is%20a%20zero%20allocation,highly%20recommended%20to%20use%20Zerolog.) post are compare them.
in general, Zerolog is fast but Less flexible than Zap and only support JSON and CBOR format after the console.
but zap supports more formats and is more flexible.

**Comment by b00f** [comment]
> only support JSON and CBOR format after the console

INMHO, we don't need any other format. What is important here is simplicity and performance.

**Comment by b00f** [comment]
Another comparison:
zerolog has about 10,000 lines of the code,
zap has about 15,000 lines of the code.

extracted using https://codetabs.com/count-loc/count-loc-online.html

**Comment by kehiy** [comment]
@b00f I think we need file core for this:
 - #495
 - 
 that's why @Ja7ad says we should use zap.

**Comment by b00f** [comment]
To write logs into the file, we can use both JSON or CBOR.

**Comment by b00f** [comment]
@kehiy replace the logrus with zerolog.

**Comment by kehiy** [comment]
> @kehiy replace the logrus with zerolog.

that's ok, should I add more config and options or just replace it?

**Comment by b00f** [comment]
Right now, just replace it. Later we think about configuration for #495

**Comment by kehiy** [comment]
ok, I will send a PR for replacing.
