### ISSUE TITLE
No fields for transaction Fee 

### ISSUE THREAD

**Issue by nagarajmanjunath** [pactus-project/pactus#590]
## Describe the problem you'd like to have solved

Cannot find `transaction fee` details in API or gRPC Call

### Describe the ideal solution

We need to create/add API/fee to calculate the total transaction fee.

**Comment by ZigBalthazar** [comment]
Hi @nagarajmanjunath , @b00f 

Please provide more information and explanations
I can do this task

**Comment by b00f** [comment]
@ZigBalthazar

Thank you for your interest in this issue.

Transaction fees in the Pactus blockchain are calculated using a percentage-based fee model. You can learn more about this model here: https://pactus.org/learn/transaction/fee/. (It is a new idea to manage the transaction pool better).

Currently, when users create transactions with their wallets, the fee is calculated and set [automatically](github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/wallet/tx_builder.go#L172C1-L172C1)). Users are not required to input it manually, even we have an [option](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/cmd/wallet/tx.go#L203) for manual fee input in the CLI.

For some offline queries, it would be beneficial to have an API that calculates transaction fees based on two parameters:

- Transaction [Payload type](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/www/grpc/proto/transaction.proto#L74C1-L74C1)
- Transactor value

We might have an API similar to: `CalculateTransactionFee(payloadType payload.Type, amount int64) int64`

**Comment by b00f** [comment]
**An Idea:**
To calculate transaction fees, you need to know the [consensus parameters](https://pactus.org/learn/consensus/parameters/) such as the Minimum Fee and Maximum Fee.
Who has this knowledge? The State is [fully aware](https://github.com/pactus-project/pactus/blob/4714af29716a9cce45560fb58702b2202c66ef85/state/state.go#L37) of the consensus parameters.
Therefore, the best place for `CalculationFee` function inside the State.
The State can expose this function to outside world.

So this PR, hits two birds with one stone: make wallet less knowledgeable, add a new API for fee calculation.
