### ISSUE TITLE
Add metrics for Peers per message type

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#605]
Similar to issue #594, we can add metrics per peer. The `sentBytes` and `receivedBytes` can be added for the [Peer](https://github.com/pactus-project/pactus/blob/dcf224206e15f1c27ad6c8d985f0bf94aefd98be/sync/peerset/peer.go#L18C1-L18C1) structure.

The only complexity here is that we should not increase the number of `sentBytes` on gossiping messages. To address this, we can add a new parameter to the `IncreaseTotalSentBytesCounter` function to obtain a pointer to the destination `peer_id`. If `peer_id` is nil, it is a broadcasting message.

Is there a better solution?

**Comment by ZigBalthazar** [comment]
Hi @b00f 

I can't find `IncreaseTotalSentBytesCounter` function in pactus

**Comment by b00f** [comment]
@ZigBalthazar I think so. If I am not mistaken it is renamed to `IncreaseSentBytesCounter`.
@amirvalhalla Please confirm.

**Comment by amirvalhalla** [comment]
@b00f 
@ZigBalthazar 
yes, we renamed `IncreaseTotalSentBytesCounter` to `IncreaseSentBytesCounter` in `peerset`
