### ISSUE TITLE
 Removing Payload prefix from transaction payload types

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#626]
Payload prefix should removed from transaction's [payload type](https://github.com/pactus-project/pactus/blob/9569722029943245887e8d194d315e0cfe671d3b/types/tx/payload/payload.go#L13). 
For example, PayloadTypeTransfer should renamed to TypeTransfer

**Comment by themantre** [comment]
@amirvalhalla Is there any other places like this?

**Comment by amirvalhalla** [comment]
> @amirvalhalla Is there any other places like this?

@themantre 
I don't think so , I've changed similar cases for `MessageType` and if I don't mistake for node response enums.
