### ISSUE TITLE
Adding wsl linter

### ISSUE THREAD

**Issue by kehiy** [pactus-project/pactus#655]

**Comment by bansaltushar014** [comment]
Hi Team,

Could you please assign this issue to me. I would like to work on it.

**Comment by kehiy** [comment]
Hi @bansaltushar014,
Glad to see you here.
I assigned it to you.
Let us know if you have any question(:

**Comment by bansaltushar014** [comment]
Hi @kehiy ,

Please review my PR.

**Comment by b00f** [comment]
We are not going to add this linter. More info: https://github.com/pactus-project/pactus/pull/791
