### ISSUE TITLE
Inability to Create Validator Address in CLI and GUI Applications

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#713]
## Describe the problem you'd like to have solved

Users are unable to create a new address for a validator, neither in the CLI nor GUI application. The `address new` command in the CLI only creates an account address.

### Describe the ideal solution

We should add a new optional flag, such as "--address_type," with values like "validator" or "bls_account." The default value should be set to "bls_account" for now.

### Alternatives and current workarounds

Currently, there is no workaround available for this issue.

---

Please close this issue when both the CLI and GUI support creating a new address for validators.

**Comment by Jaishree2310** [comment]
@themantre can you please assign this issue to be?

**Comment by themantre** [comment]
@Jaishree2310 
It is assigned to you. If you need help, join core developers in Discord.
