### ISSUE TITLE
Refactoring new node functionality

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#718]
We need to refactor the way we initialize and create the node. 
Currently, we simply obtain an address from the wallet and create the node. 

This should be changed as follows: 
First, we need to fetch all the validator addresses from the wallet, sorted by their path. 
Then, based on the number of validator addresses, we fetch the first account addresses, also sorted by their path, to use as reward addresses.

**Comment by bazooka3000** [comment]
@b00f  @themantre Should we just pass the wallet argument in the NewNode() or modify changes accordingly in the https://github.com/pactus-project/pactus/blob/1fc2f155d7b2d4903853cac366887b5bc4f3ef7c/cmd/cmd.go#L402

**Comment by b00f** [comment]
@bazooka3000 

The main idea behind this PR is to remove the [NumValidators](https://github.com/pactus-project/pactus/blob/34eff4ff1e7ac05ed54bc8c4e78c3d61566d816c/config/config.go#L42C2-L42C15) from the config file. This will fix issue #478.

Alright, let's proceed with its removal. Next, we need to find a way to extract the validator addresses from the wallet. Note that there could be between 1 to 32 addresses (zero or more than 32 should not be accepted). According to [PIP-8](https://pips.pactus.org/PIPs/pip-8), all addresses inside the wallet have a type. Therefore, we need to add a function to the wallet that returns all validator addresses within it.

This should be straightforward. Every validator address follows this path: "m/12381'/21777'/1'/*". We can iterate over all addresses, select the validator ones, sort them by the last index, and return the sorted list.

**Comment by kehiy** [comment]
@b00f I think it's already fixed on #848. we can close it now.
