### ISSUE TITLE
Unable to open a gossip bundle error

### ISSUE THREAD

**Issue by stakeworks** [pactus-project/pactus#754]
Since today I've a lot of these warnings in my log:

⛃ 1180}" bundle=null source=12D3KooWSD9U5o3hvT5houXeG5cLSNUx9Qgjedso6EFNC3GL5aq3
7:03PM WRN firewall: unable to open a gossip bundle error="invalid message: cbor: cannot unmarshal positive integer into Go struct field message.HelloAckMessage.2 of type string" _sync="{☍ 20 ⛃ 1180}" bundle=null source=12D3KooWGvAUV85sGSSXyFUaN4DKafBFFrds9q6kUU7cTg7kvfmi

After restart warnings continue

### Environment

- **Operation System:** Ubuntu 20.04.6 LTS
- **Pactus Version:** v0.15.0
- **Go Version:** Used binary from Github

**Comment by b00f** [comment]
In a P2P network, receiving malformed packets can occur. In this particular case, there is a node still running the old Testnet (Testnet-1). The log is correct, and your node simply ignored the messages that came from that node.
