### ISSUE TITLE
Add option to config for rotating logfiles

### ISSUE THREAD

**Issue by stakeworks** [pactus-project/pactus#755]
Old achieve logs are not rotated

![image](https://github.com/pactus-project/pactus/assets/19406838/7172166a-c99d-41b0-8b28-da9fd90386ae)

Add an option in the config.toml like rotate_log_after_days, which gives the user the possibility to set the number of days after the logs files are rotated.

**Comment by b00f** [comment]
Currently, we rotate the log by size (after 10 MB), not by date. This approach is simple and efficient. 
However, we can introduce an option to automatically delete old logs. For instance:

`max_backups`, which represents the maximum number of old log files to retain.

**Comment by Akshat-Jain** [comment]
@b00f I'm unable to push a branch to the repo. Do I need some permissions from your end by any chance?
```
ERROR: Permission to pactus-project/pactus.git denied to Akshat-Jain.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by b00f** [comment]
@Akshat-Jain and @himmish any update about this issue?

**Comment by Akshat-Jain** [comment]
@b00f I've raised a PR: https://github.com/pactus-project/pactus/pull/802, can you check if it suffices the requirements? Thanks!

**Comment by b00f** [comment]
@Akshat-Jain That is closed. Please cancel your attempt.

**Comment by Akshat-Jain** [comment]
@b00f Already done.
