### ISSUE TITLE
Detecting Bootstraper node

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#756]
It is necessary to detect if a node is a bootstrap node. 
One way is by adding a boolean value to the config file. 
Another way is to read all bootstrap peers in the config, and if the node's peer ID is the same as one of the bootstrap nodes, it can be marked as a bootstrap node. In this case, we keep the config intact. 

After detecting the bootstrap node, we can mark it as a `NodeServer`. You can find an example of this implementation [here](https://github.com/filecoin-project/lotus/blob/14a7ae339fa57459283cd62ce8c0070b55a39c64/node/modules/lp2p/host.go#L87).

Note: We can also prevent the "Dial to self" error message.

**Comment by b00f** [comment]
@braewoods, you may be interested in this.
