### ISSUE TITLE
Obtain the network_key id in GUI

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#761]
## Describe the problem you'd like to have solved

Users should be able to obtain the network_key ID used by LibP2P. 

### Describe the ideal solution

In the GUI, display the network ID in the "Node info" box.
The network_id can be obtained from `network` module, `SelfID()` function.

### Alternatives and current workarounds

The only current method to obtain the network key is through the log or the network API in gRPC.

**Comment by themantre** [comment]
@jemiluv8 Do you think you can fix on this issue as well?

**Comment by jemiluv8** [comment]
@themantre I could look into this but @Mukhar has already started. 
Let's see how that goes before I look to make an attempt.

**Comment by Mukhar** [comment]
> @themantre I could look into this but @Mukhar has already started. Let's see how that goes before I look to make an attempt.

@jemiluv8 I did the change but could not build and test the GUI in my system. however now I see @thesloppyguy  has already raised a PR
