### ISSUE TITLE
Add aarch64 stable release

### ISSUE THREAD

**Issue by Mr-HoDL58** [pactus-project/pactus#800]
## Describe the problem you'd like to have solved

With next release can we add another format

### Describe the ideal solution

Add aarch64 to stable releases

### Additional context
Some users have requested this.

**Comment by Ja7ad** [comment]
> ## Describe the problem you'd like to have solved
> With next release can we add another format
> 
> ### Describe the ideal solution
> Add aarch64 to stable releases
> 
> ### Additional context
> Some users have requested this.

Currently support **arm64** (aarch64) in release (https://github.com/pactus-project/pactus/releases/download/v0.16.1/pactus-cli_0.16.1_linux_arm64.tar.gz)

golang support this architectures:
```shell
linux/386
linux/amd64
linux/arm
linux/arm64
linux/loong64
linux/mips
linux/mips64
linux/mips64le
linux/mipsle
linux/ppc64
linux/ppc64le
linux/riscv64
linux/s390x

windows/386
windows/amd64
windows/arm
windows/arm64

darwin/amd64
darwin/arm64
```

**Comment by b00f** [comment]
@Mr-HoDL58 It is supported right now:
![Screenshot from 2023-11-07 17-10-41](https://github.com/pactus-project/pactus/assets/8073510/209803c9-cc2a-44ed-a1e1-3097473c1b2e)

Please double confirm.

**Comment by kehiy** [comment]
@Mr-HoDL58 @Ja7ad should we close it?

**Comment by Mr-HoDL58** [comment]
If we have that release available, yes.

**Comment by kehiy** [comment]
yes, we have it for all of the OS's.
