### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#805]
We have received many reports from users who can't run their node due to the 'Resource temporarily unavailable' error. This issue occurs when there is already a node running in the background, and users attempt to start another one. We should find a way to detect if an instance of Pactus is already running. If it is, we should inform the user before attempting to start a new node to prevent this error.

![image](https://github.com/pactus-project/pactus/assets/8073510/1e3e4079-c51d-4b14-a11d-08fdfd9dc621)

**Comment by gallardomi** [comment]
💎 $30 bounty created by b00f
🙋 If you start working on this, comment /attempt #805 to notify everyone
👉 To claim this bounty, submit a pull request that includes the text /claim #805 somewhere in its body
📝 Before proceeding, please make sure you can [receive payouts](https://docs.algora.io/bounties/payments#country-support) in your country
💵 Payment arrives in your account 2-5 days after the bounty is rewarded
💯 You keep 100% of the bounty award
🙏 Thank you for contributing to pactus-project/pactus!

**Comment by alom4hdi** [comment]
@b00f algora cannot pay to Iranians. Is there any way to make it possible?

**Comment by b00f** [comment]
@alom4hdi, we can pay the bounty to you offline. Algora is aware of this unfortunate situation. So, in case you are going to work on this issue, please make an attempt. After finishing the issue, I will contact Algora and pay you offline.

**Comment by jkcs** [comment]
Do we currently have a way to detect the running status of an instance, such as checking if a port or other resources are occupied?

**Comment by b00f** [comment]
> Do we currently have a way to detect the running status of an instance, such as checking if a port or other resources are occupied?

If a user runs two different instances, they may encounter a "Resource temporarily unavailable" error that originates from the database. This issue has been frequently reported by some users, especially when they use the "screen" application to run Pactus in the background.

![image](https://github.com/pactus-project/pactus/assets/8073510/a7408702-1fab-4755-84dd-f90f9824f92a)

Additionally, if a user wants to run two different instances of Pactus, they should use different port numbers.

**Comment by b00f** [comment]
Still we have reports from user that they see this message. 
![image](https://github.com/pactus-project/pactus/assets/8073510/c869478b-5b17-4cda-8e1e-ecdada0c103c)

@jkcs any idea?

**Comment by b00f** [comment]
Maybe because they have version 0.18 on background running.

**Comment by kehiy** [comment]
@b00f we added this to `start.go` for pactus daemon. but we doesn't add it to the GUI.

**Comment by b00f** [comment]
@jkcs can we support GUI? Return error in start node ?

**Comment by b00f** [comment]
Thanks for the update, @jkcs.
Take your time and prioritize your well-being. We can discuss the GUI when you're ready. No worries.
