### ISSUE TITLE
Include seconds in log timestamps

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#808]
Currently, log timestamps only show the minutes. 
To improve this, we should modify the logging system to include the seconds in the log timestamps.

**Comment by kehiy** [comment]
I think we have seconds already:
`"time":"2023-11-16T18:18:08Z"`

**Comment by b00f** [comment]
Not in the colorful stdout log:
![Screenshot from 2023-11-17 14-57-52](https://github.com/pactus-project/pactus/assets/8073510/a730aeea-6a69-413f-a910-46547234aa79)

**Comment by kehiy** [comment]
@b00f okay, I will fix it.
