### ISSUE TITLE
Not query gRPC server for offline commands in wallet

### ISSUE THREAD

**Issue by themantre** [pactus-project/pactus#850]
## Description

Some commands in the wallet, such as "get label," do not need to connect to any server. 
We should avoid querying the gRPC server in these commands to improve security and performance.

**Comment by kehiy** [comment]
@themantre we aren't query gRPC servers for these commands right now too.

**Comment by b00f** [comment]
So, you mean we can close this issue?

**Comment by kehiy** [comment]
Yes, as I can see we get them from valut without any network connection. I tried to find any network connection on those functions but all of them come from local data.

**Comment by themantre** [comment]
for example to create a new address we don't need to connect to any server. To test it; change the server to invalid addresses (You can change all ports to non-existing one) then try to create a new address.

**Comment by kehiy** [comment]
@themantre OK, let me test this case!

**Comment by kehiy** [comment]
@b00f @themantre 

Here is my test result:

Create command:
```sh
 ./pactus-wallet create --path=./wallet
✔ Password: |
Confirm password: 

Your wallet was successfully created at: /home/kay/code/pactus/build/wallet
Seed phrase: "***"
Please keep your seed in a safe place; if you lose it, you will not be able to restore your wallet.
```

New Address command:
```sh
 ./pactus-wallet address new --path=./wallet
✔ Label: |

pc1zhpfnxwwxsm8m2j82ry3dkcequgxv8gdxxm2ww5
```

All Address command:
```sh
./pactus-wallet address all --path=./wallet

1- pc1zhpfnxwwxsm8m2j82ry3dkcequgxv8gdxxm2ww5
```

And my wallet `servers.json` in this build was this:
```json
{
    "mainnet": [
        "localhost:50051"
    ],
    "testnet": [
        "localhost:50052"
    ]
}
```

I have no local node running for testnet or mainnet. and there was no error. I think we can close this issue.
