### ISSUE TITLE
Introduce randomness in block voting.

### ISSUE THREAD

**Issue by laosiji-io** [pactus-project/pactus#894]
## Description
I believe there is a limitation in the current voting algorithm as it requires voters to be part of the committee.
This could potentially result in a situation where if the current committee lacks the voting power to approve block creation for some reason, no new blocks would be generated, and the composition of the committee would remain unchanged, leading to a persistent deadlock.This situation would indeed lead to block congestion.

## Describe the problem you'd like to have solved

> voters being too unanimous and causing repeated failures to pass the vote.

### Describe the ideal solution

> Every validator has a chance of being selected as a voter.
> Voters who successfully vote may be elected as committee members when running for committees.

**Comment by kehiy** [comment]
Hi @laosiji-io, thank you for this. That's better to submit your idea as a PIP here:
- https://github.com/pactus-project/PIPs

This kind of changes is related to the Pactus core protocol, better to submit it there.

**Comment by kehiy** [comment]
I think this idea submitted as pip21:

https://pips.pactus.org/PIPs/pip-21
