### ISSUE TITLE
Adding Availability Score to gRPC

### ISSUE THREAD

**Issue by kehiy** [pactus-project/pactus#907]
We need to add Availability Score to gRPC module. every where we return validators info, we need to add Availability Score parameter to it.

**Comment by ZigBalthazar** [comment]
Hi @kehiy ,
Assign it to me,
I'll try my best to solve it.

**Comment by kehiy** [comment]
@jkcs @ambersun1234 @allnil 
Hi, guys have a look at this issue. tell me if you wish to assign it to you. if you are intrested.
