### ISSUE TITLE
Block time ahead from current time

### ISSUE THREAD

**Issue by kehiy** [pactus-project/pactus#909]
After implementing reachaiblity score (PIP-19), when we check network stats with our discord bot API, the block time is ahead from current time. since the but cast the int to uint we got 4,294,967,295 as time difference (it overflows). 

we need to find-out why it happens.
The issue might be due to blocks created by the second proposer. This indicates that the Availability Score is working , and validators with a low score are excluded from the block creation process. 

![Screenshot from 2024-01-04 12-47-30](https://github.com/pactus-project/pactus/assets/89645414/83044623-d493-42a4-b191-cefcb20e0a1d)

**Comment by kehiy** [comment]
![Screenshot from 2024-01-04 16-38-47](https://github.com/pactus-project/pactus/assets/89645414/c80f9d5b-2f8f-47b1-adaa-f118ae4a227b)

**Comment by themantre** [comment]
Here is the log for that specific time (12:20:20):

```
12:20:00 INF new block committed _state="{#634094 ⌘ 31236295E722 🕣 12.20.00}" block="{⌘ 31236295E722 👤 tpc1ppaa7yf5 💻 21D06C80C704 📨 3}" round=0
12:20:11 INF new block committed _state="{#634095 ⌘ 89EABA134F9E 🕣 12.20.10}" block="{⌘ 89EABA134F9E 👤 tpc1p60hcxh9 💻 64EE5FCE5DC2 📨 2}" round=0
12:20:21 INF new block committed _state="{#634096 ⌘ 3F1184665EE1 🕣 12.20.20}" block="{⌘ 3F1184665EE1 👤 tpc1pde20zfa 💻 0C2988D0DFA3 📨 3}" round=0
12:20:30 INF new block committed _state="{#634097 ⌘ 8DCD875A993C 🕣 12.20.30}" block="{⌘ 8DCD875A993C 👤 tpc1phm9r02a 💻 C8F85B6C46F0 📨 1}" round=0
12:20:41 INF new block committed _state="{#634098 ⌘ 4EEF399964F6 🕣 12.20.40}" block="{⌘ 4EEF399964F6 👤 tpc1p839j4hk 💻 EC9F9DF03AD3 📨 1}" round=0
```

Everything looks fine.

There is an explanation for this issue. Here is the code from RoboPac, `Health` command:

```go
1- currentTime := time.Now()
2- lastBlockTime, LastBlockHeight := b.cm.GetLastBlockTime()
...
3- timeDiff := (currentTime.Unix() - int64(lastBlockTime))
```

Steps that can produce this issue:

1- `currentTime` returns `12:20:04`
2- To get `lastBlockTime` , RoboPac connected to a very slow node, it got the result with some delay, after two blocks: `12:20:20`
3- `timeDiff` will be negative: `12:20:04 - 12:20:20 = -16 sec`

To fix this issue, replace line 1 and 2.

**Comment by kehiy** [comment]
@themantre so, the chain is OK? it's from bot?

**Comment by b00f** [comment]
I think so. Let's change the code in Bot and see if it happens again or not. Keep the issue open. If we can't see this anymore, we can close it later.

**Comment by kehiy** [comment]
I updated the bot code to:
```go
if strings.ToLower(m.Content) == "health" {
		currentTime := time.Now()
		lastBlockTime, LastBlockHeight := b.cm.GetLastBlockTime()
		lastBlockTimeFormatted := time.Unix(int64(lastBlockTime), 0)

		timeDiff := (currentTime.Unix() - int64(lastBlockTime))
		if timeDiff > 15 {
			msg := p.Sprintf("Network is **unhealthy❌**\nLast block time⛓️: %v\nCurrent time🕧: %v\nTime Difference: %v seconds\nLast block height⛓️: %v\nDifference is more than 15 seconds.",
				lastBlockTimeFormatted.Format("02/01/2006, 15:04:05"), currentTime.Format("02/01/2006, 15:04:05"), timeDiff, LastBlockHeight)
			_, _ = s.ChannelMessageSendReply(m.ChannelID, msg, m.Reference())
			return
		}

		msg := p.Sprintf("Network is **healthy✅**\nLast block time⛓️: %v\nCurrent time🕧: %v\nTime Difference: %v seconds\nLast block height⛓️: %v\nDifference is less than 15 seconds.",
			lastBlockTimeFormatted.Format("02/01/2006, 15:04:05"), currentTime.Format("02/01/2006, 15:04:05"), timeDiff, LastBlockHeight)
		_, _ = s.ChannelMessageSendReply(m.ChannelID, msg, m.Reference())
		return
	}
```

(this is about 2-3 days this code is running)

**Comment by b00f** [comment]
it should be:
```go
lastBlockTime, LastBlockHeight := b.cm.GetLastBlockTime()
lastBlockTimeFormatted := time.Unix(int64(lastBlockTime), 0)
currentTime := time.Now()
```

**Comment by kehiy** [comment]
got it. should be fixed now. so this is an bot issue not chain issue.
