### ISSUE TITLE
Crypto Module

### ISSUE THREAD

**Issue by kehiy** [pactus-project/pactus#955]
Currently, we are using the `github.com/kilic/bls12-381 v0.1.0` package for cryptography in Pactus, which is deprecated. we need to update this module and use a new package.

One existing approach is using Rust language for cryptography instead of Golang.

**Comment by b00f** [comment]
The `bls12-381` package from the `gnark-crypto` project looks like a good candidate here: [https://pkg.go.dev/github.com/consensys/gnark-crypto/ecc/bls12-381](https://pkg.go.dev/github.com/consensys/gnark-crypto/ecc/bls12-381).

**Comment by kehiy** [comment]
@b00f I agree. between Golang implementations it looks the most well maintained one.

Can I work on this refactor?
